### ISSUE TITLE
[Program] life_fnc_MP -> remoteExec Replacer *Not An Issue*

### ISSUE THREAD

**Issue by ColinM9991** [ArmaLife/Framework#251]
Not an issue, and I don't currently have source code as I'm not at my laptop (Pulled this from my own GitHub repo)

Here's a regex based program I made last night to replace life_fnc_MP calls with remoteExec
It works one line at a time so will not work if your life_fnc_MP parameters array is done on multiple lines, it also works recursively so drop it in in a directory at the root level with @life_server & Altis_Life.Altis folders alongside and it'll load each file and replace.

Code replaced hasn't been fully tested, does (owner _player) work as a destination value in the ["ScriptName", Target] array for remoteExec(Call)?

Replaces spawn/call accordingly with remoteExec & remoteExecCall, writes lines to console if there are any errors so you can search for that instance of life_fnc_MP & replace manually.

If you need to view source then I'd suggest JetBrains DotPeek or .NET Reflector if you haven't used a free-trial yet, source isn't pretty as it was whipped together quickly.

This post is for users who still use life_fnc_MP over heavy edits, may not serve a purpose on this exact repository.

https://www.dropbox.com/s/t8sc54k7k5hgszt/remoteExecReplacer.rar?dl=0

**Comment by clackd1amond** [comment]
Just tried it. Very useful and easy to use. Thank you, Colin!

**Comment by tkcjesse** [comment]
Awesome! Nice to see you around here offering up stuff Colin! Honestly thought you were done with Altis Life!

**Comment by ColinM9991** [comment]
I'm glad to see the community taking on the development of Altis Life further, it's only natural to release any content I've worked on.

Let me know if the true/false (etc) calls work in remoteExec for throwing the event over to a client like so

["Params"] remoteExec ["script_name", (owner _cop)]; // <-- Not sure if this works as I no longer have a gaming PC.

**Comment by NiiRoZz** [comment]
@ColinM9991 Thanks for all your work, you are the best scripter, Thanks for all

NiiRoZz

**Comment by magicianaos** [comment]
Thanks Colin!!!

**Comment by sargken** [comment]
You should add this onto the wiki @danielstuart14

**Comment by danielstuart14** [comment]
Great! Thx @ColinM9991 
I'm going to add @sargken , will just finish the server guide

**Comment by ColinM9991** [comment]
I'm aware of an issue where it uses true/false in remoteExec from life_fnc_MP

I'm going to update the executable later tonight and replace it on the existing link so it replaces true/false with the corresponding numbers.

If I'm not mistaken, false = execute on server and true = execute on clients

**Comment by ColinM9991** [comment]
Updated executable to use correct remoteExec targets.

Please correct me if I'm wrong as it has been almost 1 year since I last played Altis Life, but false = execute on server while true = execute on all clients

[[],"scriptName",true] call life_fnc_MP

In remoteExec standards the server is 2 while all clients are 0.

Also, I won't actually be supporting the RSERV macro's for remoteExec as the executable is intended for missions that don't use those (mostly) unnecessary macros.

**Comment by magicianaos** [comment]
My life server used motion script.

For example

[[player,"Acts_BoatAttacked01"],"life_fnc_animSync",true,false] spawn life_fnc_MP;

But life_fnc_MP is not support current version.

How can I change this script? help :(

**Comment by ColinM9991** [comment]
Have you even read this post, or are you just wasting time waiting for somebody to do the work for you?

**Comment by magicianaos** [comment]
Sorry about that.

But, I can't use well script.
I want to learn script.

Even I do not speak English well. I live in S.Korean
But I will try.

Thanks for aswer Colin.

**Comment by magicianaos** [comment]
Sorry about that.

But, I can't use well script.
 I want to learn script.

Even I do not speak English well. I live in S.Korean
 But I will try.

Thanks for aswer Colin.

**Comment by devShit** [comment]
i'm using 3148 i will try

**Comment by danielstuart14** [comment]
remoteExec:
2 -> Only server
-2 -> Except server (Clients)
0 -> Everyone (Server + Clients)

life_fnc_mp:
true -> Except server (Clients)
false -> Only server
nil -> Everyone (Server + Clients)

**Comment by ColinM9991** [comment]
I'll have to update the code over the weekend for that

**Comment by devShit** [comment]
hey what about cfgRemote its not generate ?

**Comment by ColinM9991** [comment]
Nothing I can do for that, you'll have custom functions I have no idea who
the target should be restricted to

**Comment by danielstuart14** [comment]
I'm going to add it to wiki.
