### ISSUE TITLE
Tear gas suggestion

### ISSUE THREAD

**Issue by Kimax89** [ArmaLife/Framework#366]
@Jawshy and i was chatting about tear gas for the cops.

Our suggestion is following.

Give cops (Sergient) the option to buy a grenade launcher for the MXC rifle and buy red smoke shells.
The red smoke will then act as tear gas by bluring the vision and halving the stamina.
The duration of this effect should be about 30 seconds.

**Comment by MrHeavyMetal** [comment]
that is a pretty cool suggestion

**Comment by Liam0** [comment]
Only addition i have is yellowsmoke would make more sense :)

**Comment by Kimax89** [comment]
Yellow smoke sounds alot better. :smile:

**Comment by Jawshy** [comment]
The tear gas script could be a modified version of one of the scripts on this [Bohemia Forum thread](https://forums.bistudio.com/topic/180844-teargas-toxic-gas-script-help/). [This one](https://forums.bistudio.com/topic/180844-teargas-toxic-gas-script-help/?p=2850713) may be the most stable.

**Comment by Jawshy** [comment]
See #410

**Comment by trinitynet** [comment]
see #414

**Comment by Kimax89** [comment]
i can see that all the pull request got closed.

Is anyone working on this?

**Comment by trinitynet** [comment]
dnt think so..

**Comment by Kimax89** [comment]
@trinitynet didnt you have some work on that?

Should i try to isolate the code from your messed up pull, and test it?

**Comment by Heavybob** [comment]
Good thing to bring back to main branch. Its a great tool for police when used and can really turn the tide during a fed.

**Comment by Kimax89** [comment]
I have tested #414 and could'nt get it to work.

**Comment by dardothemaster** [comment]
Working on it ;)

**Comment by Kimax89** [comment]
Thanks @dardothemaster 
Can't wait to test it. :D

**Comment by Kimax89** [comment]
Any progress, @dardothemaster ???

**Comment by dardothemaster** [comment]
The effect is done. Btw i am still trying to handle the script in the best
way,without loops

Il mer 30 mar 2016 17:38 Klaus Kirkeby <notifications@github.com> ha
scritto:

**Comment by dardothemaster** [comment]
Getting ready to pull! You should the close the issue

**Comment by tkcjesse** [comment]
Think this something better left to be implemented by others. Not necessarily something to be in the framework. 

@danielstuart14 if you disagree feel free to re-open.
