### ISSUE TITLE
Refuel empty fuel cans [suggestion]

### ISSUE THREAD

**Issue by clackd1amond** [ArmaLife/Framework#475]
We can refuel the vehicle. Why won't we refuel used fuel cans so that we wouldn't need to throw them away?

**Comment by Kimax89** [comment]
refueling the cans could be done at the fuel stations.

I have no idea how to script but i a simple swap from emtpy to full, wouldnt be a problem.

**Comment by Liam0** [comment]
@tkcjesse u still doing this?

**Comment by tkcjesse** [comment]
Yeah, if you have time and want to do it feel free.

I was just going to a do a simple switchero. Here's what I had: https://i.gyazo.com/1e954651c2f8aeed95475a4a98737428.png

I was just going to then do an addAction along side Nirrozs fuel station addAction.

**Comment by tkcjesse** [comment]
Done https://github.com/ArmaLife/Framework/pull/761
