### ISSUE TITLE
Configs standardization (TODO)

### ISSUE THREAD

**Issue by danielstuart14** [ArmaLife/Framework#497]
That's the next step,
 I'll update all the configs and their respective files to support the same kind of license/level check.
 Also, both virtual and weapon shops will be like vehicle and clothing shop already are. So, they'll show only the items that are available for that player.

 Also, weapon shop won't show all the tabs if there is anything on them. (Example: If there's any hat selling in the shop, this tab won't show up.)

If any of you have an idea, I'll be glad to hear.

**Comment by tkcjesse** [comment]
For those of you curious... padronization means standardization. I had to translate it. lol.

**Comment by danielstuart14** [comment]
meh, those cultural words make me crazy....

**Comment by tkcjesse** [comment]
Haha. I didn't mean it offensive! I was genuinely curious.

**Comment by danielstuart14** [comment]
nooo problem, I'll change the title. 
thx

**Comment by Heavybob** [comment]
https://github.com/ArmaLife/Altis/issues/486 - Referenced.

**Comment by MrHeavyMetal** [comment]
cant wait for this

**Comment by Liam0** [comment]
What do you guys think of this just an idea for now

https://github.com/Liam0/Altis/commit/75c2a3028d5fa7efd8223eb5a80dafd07406dabd

**Comment by danielstuart14** [comment]
@Liam0 about skins, we should update onTakeItem also.

I'll merge the fix for bail.

**Comment by Liam0** [comment]
Yeah probably a good idea, but i was just worried there was some conditions i might have overlooked so it's gonna need some testing with some custom skins.

Also have never really tried to use setvariable on (uniformContainer player) some of the reasons why i didn't make it as a pull request, would be awesome if someone would play around with it in their builds.

**Comment by tkcjesse** [comment]
@Liam0, regarding tabs. Some people have tabs to have a custom indent value. Is what it is. Whatever. Your editor may then also change it to be spaces i've noticed some that convert the tab to spaces. Lol. idk.

**Comment by Liam0** [comment]
@tkcjesse omg the headache!! lol

**Comment by danielstuart14** [comment]
yeah, almost finished. Isn't an issue anymore.
