### ISSUE TITLE
Localise all text

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#553]
Not all text is localised in the [stringtable.xml](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/stringtable.xml). Example: Altis/Altis_Life.Altis/core/actions/[fn_pumpRepair.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/actions/fn_pumpRepair.sqf#L21-L23). 

~~Once @Shield1739 has pushed [their Spanish localisations](https://github.com/ArmaLife/Altis/commit/3c9ccecfe85ffe58508e89699c944ef0447f78c7) (#542) I'll begin working on this issue.~~

**Comment by Jawshy** [comment]
How to localise [lbText](https://community.bistudio.com/wiki/lbText)? See [fn_keyGive.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/pmenu/fn_keyGive.sqf#L18) and [fn_keyDrop.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/pmenu/fn_keyDrop.sqf#L15).

**Comment by Liam0** [comment]
Those 2 are just if checks. You need to localize it in fn_keyMenu.sqf line 51, `_vehicles lbAdd localize "STR";` And the checks in those 2 files has to be changed because they woulden't work with other languages since it check for that specific text (You don't own any vehicles)

**Comment by Liam0** [comment]
Added to pull #572 it just needs a few more translations @Jawshy =)

**Comment by Jawshy** [comment]
Is it possible to localise [these text fields in the description.ext](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/description.ext#L91-L122)?

**Comment by danielstuart14** [comment]
@Jawshy, this should work:
```
class SpyGlass
	{
		title = $STR_SpyDetect_Title;
		subTitle = $STR_SpyDetect_SubTitle;
		description = $STR_SpyDetect_Descript;
		pictureBackground = "";
		picture = "";
		pictureColor[] = {0,0.3,0.6,1};
	};
```
