### ISSUE TITLE
**ATTENTION** - Regarding On-Going Development/Fixes/Etc.

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Framework#565]
Hey guys,

Just talked with @danielstuart14. A few days (April 7) back some of you may have seen the message in Gitter. If not, here ya go: https://i.gyazo.com/2e9b50de26137a1fb8178c85754b7f2b.png

Basically, we want to hold off on adding in stuff and just work on ironing out the current files. There's been a lot of people "reporting" issues/bugs in Gitter as well. If you can replicate any of those issues and they're not in the current list of issues please add them. 

@Jawshy  obviously continue to add to the stringtable since that's nothing that will potentially cause more errors or anything. 
**However, we shouldn't merge in new pull requests un-related to current content or things in the issues tab..**

@DardoTheMaster @NiiRoZz @Jawshy @danielstuart14 @sargken @Liam0 

Conversation w/ Dan regarding this: https://i.gyazo.com/8013558788366a2942a4a467bf76c37a.png

**Comment by Jawshy** [comment]
Roger that.

**Comment by tkcjesse** [comment]
Also, for the issues that others are assigned to, if you have a potential solution or something, just do a pull request. Chances are that person will be happy you offered help or another solution. (Mainly pointing towards Dan here, since he has been busy.)

**Comment by DardoTheMaster** [comment]
Copy

**Comment by DarkSilencerZA** [comment]
Paste :dash:

**Comment by Heavybob** [comment]
https://www.youtube.com/watch?v=3pHsZCml3fs

**Comment by tkcjesse** [comment]
Done.
