### ISSUE TITLE
Animation problem 1.58

### ISSUE THREAD

**Issue by adonis17** [ArmaLife/Framework#567]
animation problem since 1.58
as the super jump

**Comment by AmarokGaming** [comment]
?

**Comment by DarkSilencerZA** [comment]
?

**Comment by Heavybob** [comment]
Animation for jumping is broken and now triggers player holster weapon.

**Comment by adonis17** [comment]
yes sorry for my english (me french)

**Comment by Heavybob** [comment]
Merci :+1:

**Comment by tshowler1** [comment]
Can confirm, this triggers the holster weapon.

**Comment by GGFR-Shawn** [comment]
pareil pour moi ;)

**Comment by adonis17** [comment]
c'est à cause de la nouvelle MAJ d'arma, j'espère que bohemia va réparé ou que l'on va trouver une solution :/

this is because of the new update, I hope bohemia will be repaired or that we will find a solution :/

**Comment by Jawshy** [comment]
English, please.

**Comment by HyunsukBaek** [comment]
i have this issue too after patched 1.58

**Comment by Heavybob** [comment]
Summary of what the French said: this bug exists and would be nice if it could be fixed.

**Comment by GGFR-Shawn** [comment]
Toujours les français qui doivent faire un effort XD  mais moi je parle pas anglais désolé :D google traduction pour moi quand je veux vous comprendre ;)

French always have to make the effort XD but I don't speak Englsih sorry, and have to use Google translation when I try to understand what is said

**Comment by Liam0** [comment]
`player switchMove "AovrPercMrunSrasWrflDf";` causes this without a weapon equipped it's really weird woulden't surprise me if its something bohemia have caused.

**Comment by tkcjesse** [comment]
This probably all has to do with new animations for weapon switching on the move. I'd open debug and check the animations they have added.

**Comment by tshowler1** [comment]
For all those with the jumping issue, and haven't got a fix.. Here is my updated fn_jumpFnc.sqf script

http://paste2.org/NWGGHA5D

Works fine, just a temp fix until its completely fixed.

**Comment by adonis17** [comment]
oh nice you use weapon for animation

**Comment by adonis17** [comment]
sorry no works because spawn weapon for all player when someone jump :/

**Comment by danielstuart14** [comment]
Bohemia's fault.
 Nothing we can do, post it here: https://forums.bistudio.com
