### ISSUE TITLE
Partial Player Sync and extDB2 Repo Gone

### ISSUE THREAD

**Issue by DevenDoes** [ArmaLife/Framework#574]
First of all, the extDB2 Repository appears to have been removed.
https://github.com/Torndeco/extDB2

Secondly, I am having problems with player data fully syncing to the server. Everything seems to work fine except for cash, bank accounts, licenses, and possibly player stats. Here is what I am seeing in the extDB2 log when the manual sync button is pressed.

>[15:09:09 --4:00] [Thread 27680] extDB2: Input from Server: 1:8268:UPDATE players SET name='devito', cash='99000', bankacc='995719424', civ_licenses='"[[`license_civ_driver`,0],[`license_civ_boat`,0],[`license_civ_pilot`,0],[`license_civ_trucking`,0],[`license_civ_gun`,0],[`license_civ_dive`,0],[`license_civ_home`,0],[`license_civ_oil`,0],[`license_civ_diamond`,0],[`license_civ_salt`,0],[`license_civ_sand`,0],[`license_civ_iron`,0],[`license_civ_copper`,0],[`license_civ_cement`,0],[`license_civ_medmarijuana`,0],[`license_civ_cocaine`,0],[`license_civ_heroin`,0],[`license_civ_marijuana`,0],[`license_civ_lumberProcessor`,1],[`license_civ_rebel`,0]]"', civ_gear='"[`U_C_Poloshirt_salmon`,``,``,``,``,[`ItemMap`,`ItemCompass`,`ItemWatch`],[],[],[],[],[],[],[],[],[``,``,``,``],[``,``,``,``],[]]"', arrested='0', civ_stats='"[100,100,0]"', civ_alive='1', civ_position='"[7825.14,16122.1,112.806]"' WHERE playerid=''
[15:09:09 --4:00] [Thread 27778] extDB2: SQL_RAW_V2: Trace: Input: UPDATE players SET name='devito', cash='99000', bankacc='995719424', civ_licenses='"[[`license_civ_driver`,0],[`license_civ_boat`,0],[`license_civ_pilot`,0],[`license_civ_trucking`,0],[`license_civ_gun`,0],[`license_civ_dive`,0],[`license_civ_home`,0],[`license_civ_oil`,0],[`license_civ_diamond`,0],[`license_civ_salt`,0],[`license_civ_sand`,0],[`license_civ_iron`,0],[`license_civ_copper`,0],[`license_civ_cement`,0],[`license_civ_medmarijuana`,0],[`license_civ_cocaine`,0],[`license_civ_heroin`,0],[`license_civ_marijuana`,0],[`license_civ_lumberProcessor`,1],[`license_civ_rebel`,0]]"', civ_gear='"[`U_C_Poloshirt_salmon`,``,``,``,``,[`ItemMap`,`ItemCompass`,`ItemWatch`],[],[],[],[],[],[],[],[],[``,``,``,``],[``,``,``,``],[]]"', arrested='0', civ_stats='"[100,100,0]"', civ_alive='1', civ_position='"[7825.14,16122.1,112.806]"' WHERE playerid=''
[15:09:09 --4:00] [Thread 27680] extDB2: Output to Server: 

The full log can be seen at the following link.
http://pastebin.com/X3DacbPw

Any help is appreciated.

**Comment by tshowler1** [comment]
I have created a backup of the previously downloaded extDB2 files from torn's git.
https://www.mediafire.com/?ttc22gx6feza623

Version 71( which was the latest)

**Comment by Jawshy** [comment]
@DevenDoes, are you using the latest files from this repository and have you made any changes to the mission or server files?

**Comment by DevenDoes** [comment]
I am using the latest release. Also, I have changed no life_server files, only files in the mission.

**Comment by Jawshy** [comment]
I am not having this issue. I am using the latest files without any changes. It is possible that a change you made has caused this issue.

**Comment by DevenDoes** [comment]
I'm not sure. I haven't made any changes to anything related to money. I have made changes to licenses in the mission, but they work fine server side. For what ever reason,it just won't update those select few columns. I guess I will try replacing the life_server files with the latest ones to see if that works.

**Comment by Jawshy** [comment]
Note that I am using extDB version 70. The problem may reside within @extDB2 or altislife.sql.

**Comment by DevenDoes** [comment]
Alright. Do you have an available copy of 70 for me to test? The repository was recently taken down, so there is no other way for me to test it.

**Comment by Jawshy** [comment]
Yes, I do. Link: http://puu.sh/osqpP/e7e286a4b6.7z

**Comment by DevenDoes** [comment]
Thank you. I will give it a test, and let you know what my results are.

**Comment by DevenDoes** [comment]
The most recent version on the life_server config is missing

`class Life_Server_Settings {
	class EXTDB {
		DatabaseName = "altislife";
		DebugMode = 0;

		/* HC Setting */
		HC_Enabled = false;
	};
};`

Is this intentional? Now that I use both the latest files and 70, it fails to connect to my database, where as when I used my older files and 70, it worked just fine.

**Comment by Liam0** [comment]
it's in description.ext now.

**Comment by DevenDoes** [comment]
I tried the new description.ext file, and like I expected, it is going to require me to update all of my files, essentially wiping all of the work I have done over the past two weeks. Do you know what files MUST be changed for it to work with the new life_server setup? I recall reading that it was best just to use the releases anyways, as they are stable and not always changing.

**Comment by DevenDoes** [comment]
I have resolved the issue. When using Altis Life 4.4 R2, the fn_updateRequest.sqf file in 
life_server/Functions/MySQL/
is missing the playtime syncing features.

```
//PLAYTIME
_playtime = [_uid] call TON_fnc_getPlayTime;
_playtime_update = [];
{
	if((_x select 0) == _uid) exitWith
	{
		_playtime_update pushBack [_x select 1];
	};
} forEach TON_fnc_playtime_values_request;
_playtime_update = (_playtime_update select 0) select 0;
switch (_side) do {
	case west: {_playtime_update set[0,_playtime];};
	case civilian: {_playtime_update set[2,_playtime];};
	case independent: {_playtime_update set[1,_playtime];};
};
_playtime_update = [_playtime_update] call DB_fnc_mresArray;

switch (_side) do {
	case west: {_query = format["UPDATE players SET name='%1', cash='%2', bankacc='%3', cop_gear='%4', cop_licenses='%5', cop_stats='%6', playtime='%7' WHERE playerid='%8'",_name,_cash,_bank,_gear,_licenses,_stats,_playtime_update,_uid];};
	case civilian: {_query = format["UPDATE players SET name='%1', cash='%2', bankacc='%3', civ_licenses='%4', civ_gear='%5', arrested='%6', civ_stats='%7', civ_alive='%8', civ_position='%9', playtime='%10' WHERE playerid='%11'",_name,_cash,_bank,_licenses,_gear,[_this select 8] call DB_fnc_bool,_stats,[_this select 9] call DB_fnc_bool,_position,_playtime_update,_uid];};
	case independent: {_query = format["UPDATE players SET name='%1', cash='%2', bankacc='%3', med_licenses='%4', med_gear='%5', med_stats='%6', playtime='%7' WHERE playerid='%8'",_name,_cash,_bank,_licenses,_gear,_stats,_playtime_update,_uid];};
};
```

To solve this problem, I simply added it to the bottom and it successfully synced. Thanks for the help, and please inform me if this is a bad idea or not. I just happened to notice the difference, changed it, and it worked.
