### ISSUE TITLE
Suggestions: Alcohol, malt farming and bars.

### ISSUE THREAD

**Issue by Kimax89** [ArmaLife/Framework#582]
I think it could be fun if, we added some few alcohol like tequila, vodka and beer.

For the beer i have an idea of a new thing to harvest and proccess. You could be harvesting malt and proccess that into beer.

And then have bars wheres you can sell your beer and buy alcohol.

**Comment by sargken** [comment]
Jack Daniels come on😂

**Comment by BoGuu** [comment]
It's one of those things that communities can add themselves though. This is the 'framework' after all! I personally think a fork which has cool features in it for development would be awesome, but of which uses this repo as a framework basis.

**Comment by sargken** [comment]
@BoGuu Yes I agree with that also, its one of those things that I wouldn't mind seeing in the main build but its up to you guys what you want to do. I can mabye port the system from Altis Life Forums but idk if I got time.

**Comment by BoGuu** [comment]
@sargken 

It doesn't belong in the main build, forcing people to use something is not a good thing, considering this is a framework. A branch with these cool additions is a good idea though. We could make a enable/disable system for it all with ease, object and object addactions included.

The version of ALRPG is outdated and not worth using, it's quite quick to conjure up a new one.

**Comment by sargken** [comment]
@BoGuu A lot of things don't belong in the main build, I'm not saying you should do it or not do it. Its up to you guys. I just think its a good idea because it goes along with processing and its in the same boat and it can add more to the mission. Plus some good RP of Drinking and Driving and adding in some effects for drinking it. Its up to you guys though what you want to do.

**Comment by Kimax89** [comment]
@sargken i will actually agree with @BoGuu on this one.

We dont need anymore half-done-laggy scripts. If we gotta do it, we gotta do it right.

I agree that drinking could have a positive affect on the RPG with things like:
Tasking a taxi home, because you are too drunk.
That drunken hobo that we all know so well.
Drunk driving after spending the day at the bar.

And the whole process aspect of this one i actually good. Think about it. This is a legal job that can be used in a illegal way.

**Comment by tkcjesse** [comment]
Yeah, this isn't something I can see being needed in the build. The setup is all there. Simple stuff like adding a new resource and process. Simple stuff.... It's all on the forums. If @danielstuart14 disagrees feel free to re-open.
