### ISSUE TITLE
Wiki - SQF Syntax is wrong

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#583]
https://github.com/ArmaLife/Framework/wiki/SQF-Syntax

"Also, only spawned scripts can take use of suspension functions as "sleep" and "waitUntil". (execVM can too, but it isn't the case here.)".

This above is very wrong!

**Comment by danielstuart14** [comment]
no, it isn't: https://community.bistudio.com/wiki/sleep

**Comment by BoGuu** [comment]
Yes it is. When calling a script from a scheduled environment the called script also runs in a scheduled environment, thus allowing suspension. The only case calling wouldn't allow suspension would be from an un-scheduled enviroment, like admin console, object init etc. All the scripts in the mission file are scheduled, so it doesn't matter.

Please don't blindly read a wiki page.

For example (using editor debug console which is UN-SCHEDULED), executing the following:

[] call {diag_log "hi"; sleep 5; diag_log "bye";};

Will result in the error:

 5:28:11 Suspending not allowed in this context
 5:28:11 Error in expression <[] call {diag_log "hi"; sleep 5; diag_log "bye";};>
 5:28:11   Error position: <sleep 5; diag_log "bye";};>
 5:28:11   Error Generic error in expression
 5:28:11 "bye"

However, if we use spawn, it will create a scheduled environment (as spawn creates a scheduled environment no matter its origin).

In the debug console:

null = [] spawn {[] call {diag_log "hi"; sleep 5; diag_log "bye";};};

Result:

 5:29:42 "hi"
 5:29:53 "bye"


You seem to be lacking a core understand of the ArmA engine and how scripts are executed in certain environments.

These are a good read for you:

http://killzonekid.com/arma-scripting-tutorials-code-performance/
http://killzonekid.com/arma-scripting-tutorials-loops/
