### ISSUE TITLE
Let's talk about something serious.

### ISSUE THREAD

**Issue by danielstuart14** [ArmaLife/Framework#584]
Okay, you all know the project isn't going as it is supposed to.
So, as said, it's a framework (even the repo name is this, now), and it should stay as it.

We DO can take use of all the bohemia's features (vehicles, functions, etc), but we don't need, AND WE SHOULDN'T, add all the scripts that most servers use, just because, most servers use it. Our current mission, has many crappy scripts, that are buggy, very not optimized, and have a very fucked up syntax.

SO, HEY, STOP PUSHING SHIT HERE! I'm going to revert almost all the generic 'features', that anyone can port by himself using a tutorial somewhere. Here we need to merge things that are unique, that were tested and are the most optimized as possible.

Listen, these are some things we should do:
 Remove these useless MACROS, THEY'RE USELESS, AND JUST MAKES A SCRIPT RUN SLOWER.
 Fix ALL the remaining bugs, and override the current generic scripts, with our OWN. WE SHOULD ONLY MERGE SOMETHING FROM COMMUNITY (FORUM/ETC), IF IT DESERVES.

I'm VERY, VERY, VERY busy. Like, I had to stop my REAL stuff to write this, and yes, I promised the new "Ground Items" trunk, and some fixes, but most of them, I had to stop working, before finishing them.

Please, let's do it right. No useless macros, no generic scripts, no complications. If you want a new feature to be merged now, you'll need post all the infos about it, with a documentation, etc.

@NiiRoZz @Jawshy @tkcjesse

**Comment by trinitynet** [comment]
thank god -.-

**Comment by JohnMeiers** [comment]
:)

**Comment by DarkSilencerZA** [comment]
Finally.

**Comment by Lillymouche** [comment]
Sadly, I can do barely more than adjusting scripts to my liking, so I'm no help at all to the mission.
But from my limited point of view, I'm truly impressed by what has been done to the AL framework here.
Thanks for that!

**Comment by Wavious** [comment]
@danielstuart14 In your tutorial on how to install extdb2, I followed all instructions on what you said and I'm still getting the stting up client error. I don't understand what I'm doing wrong. I have re-installed the @extdb2 several times and whiped my database and made a new one. All the information is correct. Please help and i know your busy but this is just really frustrating me. I can give you my VM info so u can fix it for me if you want.

**Comment by Jawshy** [comment]
@Wavious, try asking for help in the [ArmaLife/Framework/Support chat-room](https://gitter.im/ArmaLife/Framework/Support).

**Comment by tkcjesse** [comment]
Seems we're back on track boys! Closing.
