### ISSUE TITLE
Vehicle Hitpoints

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#589]
This is more of a reminder to fix how damage is checked for a vehicle. For example, if you shoot out the tires on a car, it's damage will still be 0, even though its broken, thus can't be repaired.

**Comment by tkcjesse** [comment]
Eh, just need to use getDammage pretty sure

**Comment by Liam0** [comment]
getDammage returns the same as damage for me, could just make a function that check for any damaged parts with getAllHitPointsDamage then return true/false

**Comment by BoGuu** [comment]
@Liam0 

That was what the reminder was to do, I'll get round to it shortly.

**Comment by BoGuu** [comment]
@Liam0 
2d70ce74726e7a091f2188730cd942b71cc79700
