### ISSUE TITLE
Revise fn_healHospital

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#598]
The script for healing at the hospital - [fn_healHospital.sqf](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/core/actions/fn_healHospital.sqf) - is in need of a revise. 

Current issues include: 
- Possible to be in range to select medical assistance but [not within the required 5 metres](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/core/actions/fn_healHospital.sqf#L14).
- Being able to select medical assistance in rapid succession whilst being healed which will remove cash multiple times (can go into negatives). 
- **EDIT:** Does not currently use a progress bar.

**Comment by tkcjesse** [comment]
@Jawshy - https://github.com/ArmaLife/Framework/pull/599

Should be good :)
If ya wanna try it.

**Comment by Jawshy** [comment]
@tkcjesse, I shall. 

Also, it could perhaps also do with a progress bar similar to other actions like repairing.

**Comment by BoGuu** [comment]
Do you think a progress bar would suit this? The NPC is 'healing' you, you're not healing yourself. It currently displays text and still takes 8 seconds. @Jawshy

**Comment by tkcjesse** [comment]
Idk, i think having the progress bar is fine. Idk. Or care tbh either way. I'll add a config option for the price.

**Comment by BoGuu** [comment]
There would be no animation, to me it just doesn't suit at all. Stood up in game staring at a progress bar go up with no animations at a rapid speed.

**Comment by tkcjesse** [comment]
Yeah, left the progress bar since its not necessarily something you're doing yourself.. or is something that takes very long. It'd be a pretty quick progress bar...

https://github.com/ArmaLife/Framework/pull/600

**Comment by Jawshy** [comment]
#602 closes.
