### ISSUE TITLE
No house near

### ISSUE THREAD

**Issue by MrHeavyMetal** [ArmaLife/Framework#614]
So when i try to place storage boxes in my house (small or large) it says there isnt a house near, my friend who plays on the server with me has also tried and not got the same issue, i have checked the RTP and not seen any errors aswell as the EXTDB2 Logs and still no errors, any help is appreciated.

The server is running 4.4R2 on a fresh install

**Comment by BoGuu** [comment]
@MrHeavyMetal 

Sorry you say that your friend can place them just fine?

**Comment by Jawshy** [comment]
The area inside of a house where storage crates can be placed is very small and picky.

**Comment by NiiRoZz** [comment]
Hello, you use the last last files ?

Because i have put à fix, for easily place and for me it's work all the time, just launch placement when you are in your house

**Comment by MrHeavyMetal** [comment]
i downloaded the files 2 days ago via the releases section @NiiRoZz 

No my friend CANT place them,the same as me @BoGuu 
@Jawshy i have tried walking all around the house trying to place it and so as my friend, neither of us can get them to place

**Comment by BoGuu** [comment]
@MrHeavyMetal 

Would you be able to let me onto your server with enough cash to buy a house to test?

**Comment by MrHeavyMetal** [comment]
Sure thing @BoGuu here is a discord server where you can find the info to connect https://discord.gg/0ndsMobLvh1t9M0X  if you @ MrMallenby when on there (thats me) i can give you the cash

**Comment by BoGuu** [comment]
@MrHeavyMetal 

Sorry I've been quite busy. I joined your Discord, I'll usually check it quite frequently, just send me a message when you're on.
