### ISSUE TITLE
Admin Player Markers - Vehicle Marker Off-set

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#617]
When player markers are enabled the markers for players outside of vehicles will be correct. However, the markers for players inside of vehicles will be off-set from their correct position. 

See [this file](http://puu.sh/oyxlC/78ad057bfb.zip) for screenshots. 

No RPT errors.

**Comment by NiiRoZz** [comment]
Yes it's me add that because if you put in exact position you Will have problem.

For exemple if you have 3 guys inside vehicle you Will have 3 markers one over the other ...

**Comment by Jawshy** [comment]
Ah, I see.
