### ISSUE TITLE
Error in expressions - fn_mine

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#618]
The following messages are written to the client/local.rpt log file when a player presses the interaction key (Windows key) to mine a resource (had a pickaxe). 

Client/local.rpt: 
```
16:19:25 Error in expression <_resources isEqualTo  1) exitWith {
if (!(_resources select 0) isEqualType []) t>
16:19:25   Error position: <!(_resources select 0) isEqualType []) t>
16:19:25   Error !: Type String, expected Bool
16:19:25 File mpmissions\__CUR_MP.Altis\core\actions\fn_mine.sqf, line 39
```

Relevant files: 
Altis_Life.Altis/core/actions/[fn_mine.sqf](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/core/actions/fn_mine.sqf)

Full .rpt files available on request. 

Game version: [1.58.135656](https://dev.arma3.com/post/spotrep-00054)
Mission version: v4.4r2 as of d9d79200d5f82a018506dfb6a76f9d62a6b0bcad

**Comment by NiiRoZz** [comment]
b70531f75c3a08beefad6c7091ab58d6c7a0c915
