### ISSUE TITLE
Error in expressions - fn_chopShopMenu

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#619]
The following message is written to the client/local.rpt log file when a civilian sells a vehicle at a chop shop. 

Client/local.rpt: 
```
17:06:07 Error in expression <core\shops\fn_chopShopMenu.sqf"








private["_control","_price","_price","_c>
17:06:07   Error position: <private["_control","_price","_price","_c>
17:06:07   Error Local variable in global space
17:06:07 File mpmissions\__CUR_MP.Altis\core\shops\fn_chopShopMenu.sqf, line 9
```

Relevant files: 
Altis_Life.Altis/core/shops/[fn_chopShopMenu.sqf](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/core/shops/fn_chopShopMenu.sqf)

Full .rpt files available on request. 

Game version: [1.58.135656](https://dev.arma3.com/post/spotrep-00054)
Mission version: v4.4r2 as of b70531f75c3a08beefad6c7091ab58d6c7a0c915

**Comment by NiiRoZz** [comment]
Test this 34ed2a2dd7c7ef08a140e0034b9d1cf4bde0e9e9

**Comment by NiiRoZz** [comment]
Use the 2 last commit for your fix
