### ISSUE TITLE
civ_alive

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#622]
Suggestion:

Add a config option for a PERSISTENT alive/position saving (saves over restarts) OR alive/position saving between restarts. I.e, after a restart, you'll be greeted by the spawn menu.

This is obviously possible using MySQL event scheduling, however, it would be nice for communities to have an option for it, as I would imagine a lot wouldn't want position saving over a restart.

Obviously the option to disable them all would still be there.

I would appreciate feedback for this.

**Comment by Kimax89** [comment]
We allready have the last_seen column in the database, so why not set a global variable on server init with a timestamp and have everybody that was last_seen before serverstart to choose a spawnpoint.

**Comment by BoGuu** [comment]
@Kimax89 

That would be a very bad way of going about it, I have a perfect method(s) to do it, just need to know if it's wanted.

**Comment by danielstuart14** [comment]
go ahead

**Comment by Jawshy** [comment]
I'm in favour of alive/position saving between restarts.

**Comment by sargken** [comment]
Agreed

**Comment by BoGuu** [comment]
https://github.com/ArmaLife/Framework/pull/628
