### ISSUE TITLE
BattlEye logging

### ISSUE THREAD

**Issue by Felix2** [ArmaLife/Framework#625]
I haven't been able to get BattlEye logging to work on my linux server. I have the latest version and all the files in my 'battleye' folder.

I have enabled all 3 logging options in the config.

It doesn't write anything for me in the battleye folder.

Has anybody tested this on linux and gotten it working?

Am I missing something in my beserver.cfg or something?

**Comment by tkcjesse** [comment]
It surely works. Do you have any battleye logs whatsoever?

**Comment by Felix2** [comment]
@tkcjesse I do not have any logs. I'm unsure how to set it up correctly. 

Do you mean that u should add -bepath to my startup parameter?

**Comment by tkcjesse** [comment]
Yeah. You need to set battleye to run...

**Comment by tkcjesse** [comment]
https://community.bistudio.com/wiki/BattlEye

**Comment by Felix2** [comment]
@tkcjesse Ok Thanks,  I'll try it again.

**Comment by Felix2** [comment]
I've tried many different combinations but it didn't work. 

Here is how my BE folder looks like, as you can see it doesn't write logs:
![battleye](https://cloud.githubusercontent.com/assets/16271432/14917610/4568e1fa-0e20-11e6-96a4-252c27a5a3f0.png)

My startup-parameter is: ./arma3server -port=2302 -config=server.cfg -cfg=basic.cfg "-mod=life_server;extdb2" -useBE -BePath=/root/arma3/battleye

I added the "-BePath=/root/arma3/battleye" part now but it doesn't work.

To make myself clear: I've gotten the BE client to work, since I can ban people and all. The only part that isn't working is the logs that BE refuses to write...

**Comment by tkcjesse** [comment]
Battleye has nothing to do with banning people...

**Comment by tkcjesse** [comment]
You can ban people with battleye off....

**Comment by Felix2** [comment]
This is what comes up when I connect to my server: 
![welcome_be](https://cloud.githubusercontent.com/assets/16271432/14919340/a4b5968c-0e28-11e6-8a4f-3e086de07234.png)

Yes, the beserver.cfg is replaced when I'm running the server like this: beserver_active_6cdcd19e.cfg

Here is my server.cfg (I've used it for quite a while, so it's possible that it's outdated like you said)
![server](https://cloud.githubusercontent.com/assets/16271432/14919533/8cfbb41c-0e29-11e6-85d4-2c3863be08bc.png)

**Comment by BoGuu** [comment]
@Felix2 

BE is running and looking at your Gitter messages, your logs are coming up, is everything fixed/am I okay to close this? This isn't an issue with the Framework.

**Comment by Felix2** [comment]
@BoGuu I can't view any other logs than what the scripts.log generates at the moment. The money/vehicle/purchase logs still don't work.

**Comment by tkcjesse** [comment]
@Felix2 - The logs do indeed work (publicVariable.log).. 
https://i.gyazo.com/73ecf8967f521acaa455b3879a46c6ec.png

This is a problem with your setup, chances are how linux logs things. This is something that should be on the altisliferpg.com forums. This is a problem with battleye or your filters or something. If scripts.log is being generated not sure why the others wouldn't.

https://forums.bistudio.com/topic/175973-linux-server-no-rpt-file/

I'd suggest just doing the RPT method instead of the BE logs since you're apparently having issues. If you're having this many problems with Linux, it may be time to throw in the towel and go to Windows.

I'm closing this. As this is unrelated to the main build and also not the proper place for questions and  your issues not relating to the main build.

**Comment by Felix2** [comment]
@tkcjesse Thanks for taking the time to help.

I've tried using rpt logs as well but it doesn't log those events unfortunately. Perhaps it has something to do with how linux handles logs.

**Comment by tkcjesse** [comment]
Are you using stdout and stderr to log the rpt? How are you writing them?

**Comment by Felix2** [comment]
I tried using the following startup commands:

./arma3server -port=2302 -config=server.cfg -cfg=basic.cfg "-mod=life_server;extdb2" -useBE 2>>"/root/arma3/logs/arma3server_$(date +%s).rpt"

./arma3server -port=2302 -config=server.cfg -cfg=basic.cfg "-mod=life_server;extdb2" -useBE 1>>"/root/arma3/logs/arma3server_$(date +%s).rpt"

They both generated the same rpt logs:

[arma3server_1462024414.txt](https://github.com/ArmaLife/Framework/files/243638/arma3server_1462024414.txt)

My config file is set like: 
battlEye_friendlyLogging = false; 
player_advancedLog = true; 
player_moneyLog = true;

**Comment by BoGuu** [comment]
Just opened that file, it looked like this:

https://i.gyazo.com/ecee4db781ef39b706b0c2e91a19110c.png

Hehehehe

**Comment by tkcjesse** [comment]
Yeah your shits fucked.

Look at the errors....

``9:53:56 Warning Message: 'server.cfg/Missions/mission1/' is not a value``
``Starting mission:``
``9:54:09  Mission file: 1viking (__cur_mp)``
``9:54:09  Mission world: Altis``
``9:54:09  Mission directory: mpmissions\__cur_mp.Altis\``
``Can't find real path "a3\map_altis\data\roads\roads.shp": "No such file or directory"``

Also, doesn't look like anyone even connected to your server?

**Comment by Felix2** [comment]
9:54:05 Server error: Player without identity player (id 1050232410)

player is the person who joined.
