### ISSUE TITLE
PlayerInBuilding

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#631]
<del>There is some issues with the accuracy of https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/core/housing/fn_PlayerInBuilding.sqf, it gives false readings in quite a few spots inside a house (more so in certain houses). I'll have a look at reworking it some what to make it more reliable. See #614.</del>

Also, containers can be placed outside of a building (will also look into this).

<del>I think we should maybe also put the rightful author on PlayerInBuilding @NiiRoZz ...?</del>

**Comment by NiiRoZz** [comment]
I think i will redo all of this; but lineintersectwith it's the best solution

**Comment by BoGuu** [comment]
@NiiRoZz 

I'm more than happy to fix it up if you don't wish to. But please fix the author ;)

**Comment by NiiRoZz** [comment]
I don't know the autor i have picked from bohemia forum, but i will redo all this script.

**Comment by BoGuu** [comment]
Well, the way the script is doing things seems totally viable, it is indeed checking front, back, left and right walls (plus roof), but even when you are stood between 4 walls, it won't register, I'm going to test now, but I have a feeling it's a Bohemia thing aswell. The Author is written on the forum post.

**Comment by BoGuu** [comment]
Well, the way the script is doing things seems totally viable, it is indeed checking front, back, left and right walls (plus roof), but even when you are stood between 4 walls, it won't register, I'm going to test now, but I have a feeling it's a Bohemia thing aswell. The Author is written on the forum post.

**Comment by BoGuu** [comment]
@NiiRoZz 

Found the problem :+1

**Comment by NiiRoZz** [comment]
Speak me the problem in gitter please

**Comment by BoGuu** [comment]
3a7e3bb3e9cea80f059609691ce76ff75c600d82
