### ISSUE TITLE
fn_copMedicRequest

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#634]
Not sure if I'm being blind, but this doesn't exist.

https://github.com/ArmaLife/Framework/blob/1ddacf9fb3a4b8fb9eae66ef0bb3608b8b5960ec/Altis_Life.Altis/core/medical/fn_requestMedic.sqf#L18

Does anyone have an explanation?

**Comment by Liam0** [comment]
Probably just a mistake but ur not blind don't worry :P

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Framework/commit/e620c68eafafc58e067364ed3e45772ffc570aa0
