### ISSUE TITLE
Error in SQL functions, possibly just me?

### ISSUE THREAD

**Issue by Repentz** [ArmaLife/Framework#643]
I noticed my vehicles would not reset to my garage when the server restarted. Looked in RPT and found this.

http://hastebin.com/gexabobuka.md

Anyways, i decided to change my DB name to 'root'@'localhost', and it gave me this output instead

`Error StatementException: MySQL: [MySQL]: [Comment]: mysql_stmt_execute error	[mysql_stmt_error]: Unknown column ' active' in 'field list'	[mysql_stmt_errno]: 1054	[mysql_stmt_sqlstate]: 42S22	[statemnt]: CALL resetLifeVehicles`

Not sure if this is a global problem or just my issue, but I haven't done anything that would effect this.

I have also attempted this, where i only get an error output

http://www.altisliferpg.com/topic/8585-tutorial-fixing-vehicle-is-not-going-to-garages/

`[SQL]create procedure resetLifeVehicles ()BEGINUPDATE vehicles SET `active`= 0;
[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'vehicles SET `active`= 0' at line 1
`

**Comment by BoGuu** [comment]
@Repentz 

arma3'@'localhost is specifying the user 'arma3' on your local database. If your user is not arma3, this will give you the error you received. Can you run this query on your Altis Life schema:

http://hastebin.com/qovozubuja.pas

Make sure you change the 'arma3' bit to match the user that will be used to connect to the database.

**Comment by Repentz** [comment]
What fixed it was renaming the 'arma3'@'localhost' to 'root'@'localhost' 

which is my database username. Simple fix, i tried this earlier but it broke for some reason, anyways thankyou
