### ISSUE TITLE
MySQL based whitelist?

### ISSUE THREAD

**Issue by setoy** [ArmaLife/Framework#645]
Heya,

I was thinking about an appropriate whitelist tool for my server... Apparently BEC has terminated support for its tool and I've yet to find a suitable solution for my server.

Isn't that a thing that could be integrated into the ArmaLife framework (configurable)?

Any other tips on suitable whitelist solutions?

Cheers

**Comment by tkcjesse** [comment]
Are you talking for like cops or just all players?

**Comment by BoGuu** [comment]
@setoy 

Make it so the blacklist column in the database must be 1 for somebody to enter. Edit it to no longer support whitelisted factions and instead add it to initilisation.

**Comment by setoy** [comment]
@tkcjesse Nope, I didn't realize that. Thank you, though! :D

@BoGuu Or like that, yeah. Thanks!

**Comment by BoGuu** [comment]
Welcome

**Comment by tkcjesse** [comment]
You can just change the select statement in the conf and adjust the table to be your players table if you want it to be that and then change the columns or add columns as you need.

**Comment by setoy** [comment]
Sorry, it's me again... Is there a tutorial on how to set this up? I created a new table with 0 entries in the database that I configured at [altislife] but players can still connect even though my whitelist is active.

The port is the RConPort I specified in the BEServer.cfg

    [Rcon]
    ;; This is functional, should be working fine. Just needs abit of testing on a $
    ;; Allow for changing Address for those running server in a VM environment.
    IP = 127.0.0.1
    Port = 2305
    
    ;; Rcon Password i.e Battleye/beserver.cfg
    Password = myrcon
    
    ;; Bad Player Name Checks
    ;;		This will only work if your mission / mod has started extDB2 Rcon. i.e 9:START_RCON:RCON
    Bad Playername Enable = false
    Bad Playername Kick Message = Bad Player Name
    
    ;; By default : is a bad character (used as seperator for extDB2 Calls (this is hardcoded in)
    ;;Bad Playername Strings = (:):{:}
    ;;Bad Playername Regex_1 = [:alnum:]
    ;;Bad Playername Regex_2 = [:alnum:]
    ;;Bad Playername Regex_3 = [:alnum:]
    
    
    ;; Whitelisting / Reserve Slots
    ;;		This will only work if your mission / mod has started extDB2 Rcon. i.e 9:START_RCON:RCON
    Whitelist Enable = true
    Whitelist Kick Message = Whitelist: www.google.com
    
    Whitelist Public Slots = 0
    
    ;; Database settings to use (Optional)
    Whitelist Database = altislife
    Whitelist SQL Prepared Statement = SELECT CASE WHEN EXISTS(SELECT steam64_id FROM `whitelist` WHERE battleye_guid=? AND is_whitelisted=1) THEN 1 ELSE 0 END
    Whitelist Kick on SQL Query Failed = true
    
    ;; Hardcoded BEGuids for whitelisted players
    ;Whitelist BEGuids = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx : yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
