### ISSUE TITLE
Spacing Guideline

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#646]
Can we please agree on either tabs or spaces (and how many), and stick to this guideline no matter what?

Pull requests can be checked and all contributors should stick to this by default (just change your editors settings).

**Comment by tkcjesse** [comment]
Why the hell would you use 4x spaces? Where is this practiced? Russia?

**Comment by BoGuu** [comment]
Tabs to 4 spaces is quite normal. 

If the collaborators follow it, then checking pull requests is actually quite easy, fear not!

**Comment by Jawshy** [comment]
Voting via comments would probably have more integrity than over a Straw Poll. 

Anyway, I prefer using a **tab** equal to 4 spaces.

**Comment by Heavybob** [comment]
Tab is best.

**Comment by BoGuu** [comment]
@Jawshy 

It would indeed, I'll sort something out for that shortly.

**Comment by tkcjesse** [comment]
> Voting via comments would probably have more integrity than over a Straw Poll.
> Anyway, I prefer using a tab equal to 4 spaces.

@Jawshy. Um excuse me who are you to tell my friends they cannot vote in this poll? As well as me clearing my browser cache/history and re-vote? Haha. I really didn't do this but yeah... strawpolls.

**Comment by sargken** [comment]
4 spaces

**Comment by BoGuu** [comment]
For the reason mentioned initially by @tkcjesse "since there's so many fingers being shoved into this", I've had a chat with Daniel and it's been decided that we will indeed stick to 4 spaces. I'm about to update all the files that contain tabs to spaces and all commits and pulls should maintain this. I'm in no doubt the members here will stick to this but please can you also check that pull requests use spaces. Just highlight over the trailing space, they appear as spaces on the browser, not tabs.

**Comment by BoGuu** [comment]
Meet Travis:

https://travis-ci.org/ArmaLife/Framework/builds/129292054
