### ISSUE TITLE
Transaction logging working partially 

### ISSUE THREAD

**Issue by Felix2** [ArmaLife/Framework#653]
The logging of withdraws, transfers, Vehicle purchases and more are only working partially for me. The name of the player who made the transaction is missing. All other info about transaction amount and type of purchase is there though.

I'm using Linux, which probably has something to do with why it doesnt work, since on windows servers ive heard it works. 

The death_log works fine for me though.

I'm using the latest devbranch.

**Comment by tkcjesse** [comment]
Do you have befriendly logging set to true??

**Comment by Felix2** [comment]
All logging options are set to true.

**Comment by tkcjesse** [comment]
Why... you're obviously using the rpt log. Set the befriendly option false. Then this "problem" will be solved.

**Comment by Felix2** [comment]
I will test and check.

**Comment by Felix2** [comment]
It worked now when i disabled be-logging! 

Thank you
