### ISSUE TITLE
long queries with slow databases

### ISSUE THREAD

**Issue by danielstuart14** [ArmaLife/Framework#655]
Long queries are returning "null" if the database is slow.
That seems to be, because there isn't enough time, and the script just parses what it has.

Here, is an example: 
Garage requests a long query, with slow databases, it isn't showing up the vehicles.
Log (pid removed):
```
"------------- Client Query Request -------------"
"QUERY: SELECT id, side, classname, type, pid, alive, active, plate, color FROM vehicles WHERE pid='XXXXXXXXXXXX' AND alive='1' AND active='0' AND side='civ' AND type='Car'"
"Time to complete: 0.0619965 (in seconds)"
"Result: <null>"
"------------------------------------------------"
```

If you are having this issue, there're two "workarounds".
You can use debug version of extDB2.dll, or, you can revert these commits:
https://github.com/ArmaLife/Framework/commit/1e42bde03b51b60d45d3f028f40e4276c0f1b9b1
https://github.com/ArmaLife/Framework/commit/d219a2e84d518570911e86ec9d929db5add2c2df

Idk if it's related to extDB, but, seems that doing diag_log, script is delayed a little.

**Comment by BoGuu** [comment]
I'm going to rejig asynccall shortly, and will find a work around for the suspension without needing to run this scheduled.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Framework/commit/d15feb02304512aa885e07798737ace132052469

Great! :beers:
