### ISSUE TITLE
Compatibility with the 3Den editor [Enhancement]

### ISSUE THREAD

**Issue by MrHeavyMetal** [ArmaLife/Framework#663]
Since the 3Den editor is so useful i think it would be great if the Framework worked with it(if possible)

**Comment by BoGuu** [comment]
I'm not one to be rude, but have you even tried?

**Comment by MrHeavyMetal** [comment]
If i remember correctly i saw a issue a couple weeks back about the mission file breaking as in statements etc not working when imported to the new format

**Comment by BoGuu** [comment]
Why don't you try load the map up in Eden?

**Comment by MrHeavyMetal** [comment]
NVM i fucked up apparently its been fixed, feel free to close this

**Comment by BoGuu** [comment]
:+1:
