### ISSUE TITLE
Some Macro Removal

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#664]
Quite a few of the macros currently used are either really not needed, or do not save any time. Macros will not affect performance, however the following actually make code less readable and do not save any time or effort. I'll update this list if there is any others agreed upon, but it would be appreciated if people can work their way down removing occurrences and reference this issue in the pull (please pull them, do not directly commit them).

CONFIG_VEHICLES - Complete
CONFIG_LIFE_VEHICLES - Complete
CONFIG_WEAPONS - Complete
CONFIG_MAGAZINES - Complete
CONFIG_GLASSES - Complete
EQUAL(condition1,condition2) - Complete
grpPlayer - Complete
steamid - Complete
SEL(ARRAY,INDEX) - Complete
SUB(var1,var2) - Complete
ADD(var1,var2) - Complete
RIFLE - Complete
RIFLE_ITEMS - Complete
PISTOL - Complete
PISTOL_ITEMS - Complete
LAUNCHER - Complete

**Comment by Jawshy** [comment]
If I correctly recall, last time macros were removed the commit was reverted shortly thereafter. Will that not be the case this time? Can we make a choice whether to or not to remove the superfluous macros and stick to it?

**Comment by NiiRoZz** [comment]
I think config_vehicle don't need to Remove, it's more redeable for anyone but other can Remove it

And before à pull request deleted all macros just delete macro don't needed

**Comment by tkcjesse** [comment]
@NiiRoZz it definitely didnt delete all the macros you should probably have
a look if thats what you think. It actually deleted basically all whats
listed. Not even that entire list...

**Comment by tkcjesse** [comment]
Was gonna update your list. However, also removed:

GVAR_PNAS
GVAR_UINS
GVAR_MNS
SVAR_PNAS
SVAR_PNS
SVAR_UINS
SVAR_MNS
GVAR
SVAR
CASH
BANK

**Comment by NiiRoZz** [comment]
560e11188f2b5dd64bf0031d1852a1d5dbb22064

**Comment by tkcjesse** [comment]
@NiiRoZz were you getting the others or do you want me to continue on some of these?

**Comment by BoGuu** [comment]
@NiiRoZz 

Can we remove all uses before removing the macro please?

**Comment by tkcjesse** [comment]
@BoGuu is there a few EQUALs still?

**Comment by Jawshy** [comment]
> LAUNCHER - Complete

[Nope](https://github.com/ArmaLife/Framework/issues/700).

**Comment by tkcjesse** [comment]
Should be the last of the list...

https://github.com/ArmaLife/Framework/pull/749/files

**Comment by tkcjesse** [comment]
Completed the list. Woo!
