### ISSUE TITLE
Federal reserve - Fix doors?

### ISSUE THREAD

**Issue by Repentz** [ArmaLife/Framework#670]
Can't seem to find any code relating to fixing the doors on the federal reserve as a cop. Am I missing something here? I can find vault, not doors.

**Comment by BoGuu** [comment]
https://github.com/ArmaLife/Framework/blob/2f35c1715ac604ac4f2cc76943f4bbab5d927a41/Altis_Life.Altis/core/cop/fn_repairDoor.sqf
