### ISSUE TITLE
Error in expression - fn_initSpy

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#672]
The following message is spammed tens of thousands of times in the client/local RPT log file when loading into the game: 

```
16:14:54 Error in expression <oft_F_Heli_Crusher_UGV"
];

getVariable uiNamespace getVariable setVariable["Rsc>
16:14:54   Error position: <uiNamespace getVariable setVariable["Rsc>
16:14:54   Error Missing ;
16:14:54 File mpmissions\__CUR_MP.Altis\SpyGlass\fn_initSpy.sqf, line 136
```

##### Reproducible: 
- Yes, every time. 

##### Relevant files: 
- Altis_Life.Altis/SpyGlass/[fn_initSpy.sqf](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/SpyGlass/fn_initSpy.sqf)

Full RPT files available upon request. 

Game version: [1.58.135742](https://dev.arma3.com/post/spotrep-00055)
Mission version: v4.4r2 as of https://github.com/ArmaLife/Framework/commit/e337b75845ba2b5cf387176ff2ccfcfa9933c20e

**Comment by tkcjesse** [comment]
Resolved in above ^.
