### ISSUE TITLE
Error in expressions - bank

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#673]
### 1

The following message is written to the client/local RPT log file: 

```
16:18:35 Error in expression <    if(isNil "_ret") exitWith {};

    [BANK,CASH,owner player,player,profileNam>
16:18:35   Error position: <BANK,CASH,owner player,player,profileNam>
16:18:35   Error Undefined variable in expression: bank
```

##### Reproducible: 
- Yes, but unknown how to. 

##### Relevant files: 
- ?

### ~~2~~

~~The following message is written to the client/local RPT log file when the player's pay check is due:~~ 

```
16:58:00 Error in expression < life_paycheck) + 1500;
} else {
BANK = BANK + (call life_paycheck);
systemChat >
16:58:00   Error position: <BANK + (call life_paycheck);
systemChat >
16:58:00   Error Undefined variable in expression: bank
```

~~The system chat will say that the player received their pay check of X amount, but no money will be added to their account.~~ 

##### ~~Reproducible:~~ 
~~- Yes, every time.~~ 

##### ~~Relevant files:~~ 
~~- ?~~

Full RPT files available upon request. 

Game version: [1.58.135742](https://dev.arma3.com/post/spotrep-00055)
Mission version: v4.4r2 as of https://github.com/ArmaLife/Framework/commit/e337b75845ba2b5cf387176ff2ccfcfa9933c20e

**Comment by tkcjesse** [comment]
Resolved in above ^.

**Comment by Jawshy** [comment]
Still getting the first error.
