### ISSUE TITLE
Suggestion: Weapons

### ISSUE THREAD

**Issue by tshowler1** [ArmaLife/Framework#674]
Would it be hard to make in the Config_Master a time setting for gun despawn time?

I know I'd like it, not sure how to go about it, but also a few other people would want it....

**Comment by BoGuu** [comment]
Are you guns disappearing instantly or something?

**Comment by tshowler1** [comment]
When another player gets to the dead body, they almost instantly disappear, doesn't give the other play any time to pick them up.

**Comment by tkcjesse** [comment]
Thats intended to prevent duping.
