### ISSUE TITLE
Can't stop escorting

### ISSUE THREAD

**Issue by clackd1amond** [ArmaLife/Framework#682]
When escorting a player, the interaction menu doesn't appear, so only other cop can detach a player from you.

**Comment by tkcjesse** [comment]
What version are you running and is it vanilla? Because I was just using this like a week ago and it was fine. I even used it on civilians all i modified was the array that checks playerside...

**Comment by clackd1amond** [comment]
Using all latest commits

**Comment by clackd1amond** [comment]
It seems, this fixed the problem https://github.com/ArmaLife/Framework/commit/34749422cfab08be101174feb9a7f23b96f0248e LOL

**Comment by BoGuu** [comment]
That commit won't have fixed your problem, it seems you may have fixed it yourself without realising
