### ISSUE TITLE
Tazing the dead

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#683]
If somebody is dead and a cop tazes them, their corpse teleports to debug island.

**Comment by Jawshy** [comment]
https://github.com/ArmaLife/Framework/commit/0432cdcb234177a59e17dc1f2eee53d7183e82f2 reverted https://github.com/ArmaLife/Framework/commit/32d6f7cebe4a8ddceec7f45f8c9af7fcb94c5083. Reopening.

**Comment by BoGuu** [comment]
Reminder to fix #738 (the handledamage part)

**Comment by tkcjesse** [comment]
Fixed - https://github.com/ArmaLife/Framework/pull/799
Tested w/ @Jawshy.
