### ISSUE TITLE
Modded Vehicles not storing in garage

### ISSUE THREAD

**Issue by Blaxqwood** [ArmaLife/Framework#685]
Having Issues with using modded vehicles on 4.4 (CUP Vehicles & Jonzie Pack) not being found when trying to store the vehicle, i am being told "There isn't a vehicle near the NPC".

I have executed "hint str ((nearestObjects [player, ["Car"], 100]) - [player]); [] spawn { sleep 5; systemChat str " in debug and it is giving a positive result that the car is in the parent directory as "Car" but is still not being found when attempting to store.

 anyone know a fix/way around this issue?

**Comment by Jawshy** [comment]
Hi. Issues isn't the correct place to ask for help about problems outside of the current vanilla build. Please seek help elsewhere such as in our [support chat room on Gitter](https://gitter.im/ArmaLife/Framework/Support).

**Comment by sargken** [comment]
The mods need to be run on the server
