### ISSUE TITLE
Can't buy houses [BUG]

### ISSUE THREAD

**Issue by Latouth** [ArmaLife/Framework#704]
So if you go install latest version of Arma 3 server and put latest version of extDB2 and latest version (4.4) of Altis life on it, and try to buy a house it will say either "Can't afford to buy this house" (even if it's a 5 mill house and my cash is 30 mill) or "Someone else already owns this" I used everything latest on this repo, I've also tried this with infiStar admin menu, but that wouldn't modify this.

**Comment by Jawshy** [comment]
I managed to buy a house with no issue using files as of https://github.com/ArmaLife/Framework/commit/4b8cda2a49e6a536ba564f61aa3dac8f9aaf44ea.

**Comment by Latouth** [comment]
I have a housing license, and I had 1 Bill in my bank.
From "life_atm_cash = 999999999" for 1 bill bank and I did life_cash for 30 mill aswell.
Well my concern is it's saying "Someone already owns this house"

**Comment by Jawshy** [comment]
Does it says the house is owned in the database?

**Comment by Latouth** [comment]
It's a fresh server, no one owns any thing. 
I'll start up the server and check

**Comment by Latouth** [comment]
Seems having 30 mill in bank instead of 1 bill works...

I had 1 bill bank, and 30mill cash, so i put 30m in cash & bank and it worked.

**Comment by tkcjesse** [comment]
It's probably due to how Arma handles numbers... anything above 1 million is in the form of exponents. Could possibly have to do with the fact you did a billion...
