### ISSUE TITLE
Error in expressions - fn_fuelSupply

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#712]
The following message is written to the client/local.rpt log file when a player supplies fuel to a gas station by using a fuel truck ([fuel missions](https://github.com/ArmaLife/Framework/pull/351)): 
```
16:34:28 Error in expression <Tank_Empty","PLAIN"]};
sleep 2;

CASH = CASH + _win;
[0] call SOCK_fnc_updatePar>
16:34:28   Error position: <CASH + _win;
[0] call SOCK_fnc_updatePar>
16:34:28   Error Undefined variable in expression: cash
16:34:28 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_fuelSupply.sqf, line 121
```

##### Reproducible: 
- Yes, every time. 

##### Relevant files: 
- Altis_Life.Altis/core/vehicle/[fn_fuelSupply.sqf](https://github.com/ArmaLife/Framework/blob/bdf4ccad883b9d470451ec995cce60cb8e98384d/Altis_Life.Altis/core/vehicle/fn_fuelSupply.sqf)

Game version: [1.60.136052](https://forums.bistudio.com/topic/183855-release-candidate-branch-announcements/?p=3023745)
Mission version: v4.4r2 as of https://github.com/ArmaLife/Framework/tree/5aab9a7f9ecbea0b824f3864d9d942cd2657303f

**Comment by Liam0** [comment]
it's just because its not including macros, but im not really up to date while the macro removal process is going on =)

**Comment by BoGuu** [comment]
bd08f4d0b89a77c7e22d6832c792d5b55e31f2c0
