### ISSUE TITLE
Starting extDB2 rcon with life_server

### ISSUE THREAD

**Issue by setoy** [ArmaLife/Framework#714]
I'm currently trying to implement the whitelist using extDB. For that I've created a new table in the database I've configured in extDB config. However, no check is being performed and every player can join, even when they're not on the whitelist (in fact the table is totally empty).

The port is the RConPort I specified in the BEServer.cfg (because of the 1.58 changes).

    [Rcon]
    ;; This is functional, should be working fine. Just needs abit of testing on a $
    ;; Allow for changing Address for those running server in a VM environment.
    IP = 127.0.0.1
    Port = 2305
    
    ;; Rcon Password i.e Battleye/beserver.cfg
    Password = myrcon
    
    ;; Bad Player Name Checks
    ;;		This will only work if your mission / mod has started extDB2 Rcon. i.e 9:START_RCON:RCON
    Bad Playername Enable = false
    Bad Playername Kick Message = Bad Player Name
    
    ;; By default : is a bad character (used as seperator for extDB2 Calls (this is hardcoded in)
    ;;Bad Playername Strings = (:):{:}
    ;;Bad Playername Regex_1 = [:alnum:]
    ;;Bad Playername Regex_2 = [:alnum:]
    ;;Bad Playername Regex_3 = [:alnum:]
    
    
    ;; Whitelisting / Reserve Slots
    ;;		This will only work if your mission / mod has started extDB2 Rcon. i.e 9:START_RCON:RCON
    Whitelist Enable = true
    Whitelist Kick Message = Whitelist: www.google.com
    
    Whitelist Public Slots = 0
    
    ;; Database settings to use (Optional)
    Whitelist Database = altislife
    Whitelist SQL Prepared Statement = SELECT CASE WHEN EXISTS(SELECT steam64_id FROM `whitelist` WHERE battleye_guid=? AND is_whitelisted=1) THEN 1 ELSE 0 END
    Whitelist Kick on SQL Query Failed = true
    
    ;; Hardcoded BEGuids for whitelisted players
    ;Whitelist BEGuids = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx : yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

Apparently I'd need to enable extdb rcon and have done so in the life_server\init.sqf right after the result of `ADD_DATABASE_PROTOCOL` (line 47):

        _result = EXTDB "9:START_RCON:RCON";
        if (!(_result isEqualTo "[1]")) then {throw "extDB2: Error with rcon shit"};

Apparently, the rcon system is starting (according to the extDB logs), but still every player can connect even though the table is empty...

**Comment by tkcjesse** [comment]
Github Issues are meant for issues with the current Repository. Please seek support in the gitter.im support channel or on the altisliferpg.com site. This is not the proper place for this as it is not a repository issue.
