### ISSUE TITLE
money doesn't drop on the ground. 

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Framework#716]
when player died, money doesn't drop on the ground. 
66284f5c7458e4e106ab0a5158679d04fd6ecee4

**Comment by Jawshy** [comment]
Ease off the caps, please. Also, commit link does not work.

**Comment by HyunsukBaek** [comment]
in fn_dropItems.sqf,  32d6f7cebe4a8ddceec7f45f8c9af7fcb94c5083

i changed ( revert) as follows, it working well. 

case "life_cash": {
             if (CASH > 0) then {
                 _pos = _unit modelToWorld[0,3,0];
                 _pos = [SEL(_pos,0), SEL(_pos,1), 0];
                 _obj = "Land_Money_F" createVehicle _pos;
             };
         };
     };
} forEach (("true" configClasses (missionConfigFile >> "VirtualItems")) + ["life_cash"]);

**Comment by Jawshy** [comment]
By "gold" did you mean [pile of money](https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EMPTY#Land_Money_F) or [gold bar](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/Config_vItems.hpp#L131-L137)?

**Comment by HyunsukBaek** [comment]
@Jawshy not gold. it's money($$$ cash ) 
sorry my fuxxed english.

**Comment by BoGuu** [comment]
Can this be test with https://github.com/ArmaLife/Framework/commit/2a70fb51946621536baf3ca9679d89caf78fd39a

**Comment by Jawshy** [comment]
> Can this be test with https://github.com/ArmaLife/Framework/commit/2a70fb51946621536baf3ca9679d89caf78fd39a

Confirmed working.
