### ISSUE TITLE
tazer doesn't working 

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Framework#717]
tazer gun doen't working i patched 32d6f7cebe4a8ddceec7f45f8c9af7fcb94c5083

**Comment by Jawshy** [comment]
Ease off the caps, please. Also, commit link does not work.

**Comment by setoy** [comment]
I second that. I thought it would be happening because of @NiiRoZz changes I'm still using in my mission regarding the suicide vest (https://github.com/ArmaLife/Framework/commit/e6d44278135d360f9e7019f51e03439989c5cf3c#diff-c02893a54f6dd79132d1ca9932b6881bR47), but it's not that.

Sometimes the tazer is lethal (well, more often than it is not :D)

**Comment by Jawshy** [comment]
@setoy, I've never had the Taser go lethal. Do you know under what circumstances?

**Comment by setoy** [comment]
I'll try to get this reproduced.

**Comment by tshowler1** [comment]
I can confirm this actually happens.

An admin on my server "tazed me" and it actually kills me sometimes... Big error, and also tazor rifle (SDAR) does same thing sometimes.

**Comment by HyunsukBaek** [comment]
I DELETED "if (!(_unit getVariable["Revive",false])) exitWith {};" THIS CODES (REVERT), THEN IT WORKING WELL.

**Comment by Jawshy** [comment]
@tshowler1, just to confirm. The files that handle the Tazer on your server are up-to-date with those on this depository? 

@HyunsukBaek, so this commit https://github.com/ArmaLife/Framework/commit/32d6f7cebe4a8ddceec7f45f8c9af7fcb94c5083 is causing the issue. Also, ![](http://www.thehindu.com/multimedia/dynamic/01126/Fwd28mp_Caps_Lock__1126390f.jpg)

**Comment by HyunsukBaek** [comment]
@Jawshy  i like your finger. hh... kidding.

so, i don't understand your comment.

**Comment by Liam0** [comment]
Just change it to,

`if (_unit getVariable["Revive",false]) exitWith {};`

Should do the trick for you

**Comment by BoGuu** [comment]
Grr...

**Comment by HyunsukBaek** [comment]
@Liam0 another problem. when a cop get off a vehicle at that time shot tazer to someone, then someone killed by cop. no tazed.

**Comment by tshowler1** [comment]
@Jawsh - I will confirm shortly! Give me about 10 min.

**Comment by Liam0** [comment]
@HyunsukBaek i'm sorry i don't understand what the other problem is

**Comment by BoGuu** [comment]
The script that handles the damage, is, not really the issue. It will return 'no damage', if you will, if the player is using a tazer variant, and is further away than the preset ranges, and if he's within that range, it will taze. It's ARMA that's the issue, like many things. Ofcourse we could look into something to perhaps fix this, but as it stands ¯\_(ツ)_/¯
