### ISSUE TITLE
Warning Message: No entry - MapView.LineMarker

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#719]
**Note that this issue will only occur on [1.60.136125](https://forums.bistudio.com/topic/183855-release-candidate-branch-announcements/?p=3023745) RC.** 

The following message is written to the client/local.rpt log file when the player is at the spawn screen (on mission join or respawn): 
```
 1:29:27 Warning Message: No entry 'mpmissions\__CUR_MP.Altis\description.ext/life_spawn_selection/controlsBackground/MapView.LineMarker'.
 1:29:27 Warning Message: No entry '.lineWidthThin'.
 1:29:27 Warning Message: '/' is not a value
 1:29:27 Warning Message: No entry '.lineWidthThick'.
 1:29:27 Warning Message: '/' is not a value
 1:29:27 Warning Message: No entry '.lineDistanceMin'.
 1:29:27 Warning Message: '/' is not a value
 1:29:27 Warning Message: No entry '.lineLengthMin'.
 1:29:27 Warning Message: '/' is not a value
```

##### Reproducible: 
- Yes, every time. 

##### Relevant files: 
- Altis_Life.Altis/[description.ext](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/description.ext) ?

Game version: [1.60.136125](https://forums.bistudio.com/topic/183855-release-candidate-branch-announcements/?p=3023745) 
Mission version: v4.4r2 as of https://github.com/ArmaLife/Framework/commit/467bd77dbbc7446425ea66a559b232907a3ab982

**Comment by BoGuu** [comment]
I'll give you a fix for this when my 1.60 downloads

**Comment by BoGuu** [comment]
Add: http://hastebin.com/aqaqudoses.avrasm

To common.hpp as a class of Life_RscMapControl:

https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/dialog/common.hpp#L738

In the same fashion as the rest

**Comment by Jawshy** [comment]
Your fixed worked . Please make a pull request for it.

**Comment by BoGuu** [comment]
@Jawshy 

Add it to your SpyGlass commit, 1.60 isn't out yet.

**Comment by Jawshy** [comment]
Okay, but I'll make another one as it's a separate issues.
