### ISSUE TITLE
error in core/shops/fn_weaponShopMenu.sqf

### ISSUE THREAD

**Issue by Oratorian** [ArmaLife/Framework#723]
Error Undefiened Variable in expression : _level
    _level = missionNamespace getVariable _levelName; <- Line 34
    if(_level isEqualType {}) then {_level = FETCH_CONST(_level);}; <- line 35

**Comment by Jawshy** [comment]
@Oratorian, I am unable to reproduce this issue. What steps did you take to reproduce this issue?
