### ISSUE TITLE
goldbar can't get from safe!. 

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Framework#729]
i used voltcutter and blasting charge to open safe . 

and then, safe is opened and i confirmed 170 goldbars but, 

some notification messages war shown and can't get it !

**Comment by Jawshy** [comment]
@HyunsukBaek, what did the notification message say? Where there [enough cops online](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/Config_Master.hpp#L42)?

**Comment by BoGuu** [comment]
c6d40d5ace727885cba9a3cb26e8fdfe265fe2a9

**Comment by HyunsukBaek** [comment]
@BoGuu @Jawshy 
here is a captured screen of this problem .
@BoGuu  thx, i will test tonight ur patch . 

and, nowadays, there are so many trifling error in this master repository. 
plz do test more before you merge it, thxs.


![20160521193117_1](https://cloud.githubusercontent.com/assets/5819861/15447893/6906def6-1f8b-11e6-8a2a-a1c6df7b4375.jpg)

**Comment by tkcjesse** [comment]
@HyunsukBaek This has been this way pre 4.0 I'm almost certain. Surely since 4.0, before Dan even had control of the stuff... This was none of us. It was Tonic or Yuka.
