### ISSUE TITLE
Zero divisor in clothing filter

### ISSUE THREAD

**Issue by setoy** [ArmaLife/Framework#732]
Simply opening the clothing store:

    17:39:32   Error Type Any, expected String
    17:39:32 File mpmissions\__CUR_MP.Altis\core\shops\fn_clothingFilter.sqf, line 105
    17:39:32 Error in expression <e_fnc_fetchCfgDetails;
    _pic = (_details select 2);
    };
    
    if (!(_levelValue isEqual>
    17:39:32   Error position: <select 2);
    };
    
    if (!(_levelValue isEqual>
    17:39:32   Error Zero divisor
    17:39:32 File mpmissions\__CUR_MP.Altis\core\shops\fn_clothingFilter.sqf, line 66
    17:39:32 Error in expression <ualTo "") then {
    _list lbAdd ((_details select 1));
    } else {
    _list lbAdd _displa>
    17:39:32   Error position: <select 1));
    } else {
    _list lbAdd _displa>
    17:39:32   Error Zero divisor

**Comment by BoGuu** [comment]
I can't reproduce this using the repo build, it would seem a problem on your end. What items are in your shop?

**Comment by setoy** [comment]
http://pastebin.com/z7U5vU67

**Comment by BoGuu** [comment]
Which shop?

**Comment by setoy** [comment]
Clothing (as apparent from my paste :))

**Comment by BoGuu** [comment]
Which class..

**Comment by setoy** [comment]
Apparently I don't understand what kind of information you require from me...

**Comment by BoGuu** [comment]
Which clothing shop did you open?

bruce?
cop?
medic?

**Comment by setoy** [comment]
Bruce

**Comment by BoGuu** [comment]
Does it happen with any others? Like the cop one?

**Comment by setoy** [comment]
No, it doesn't happen with either the cop nor the medic one.

**Comment by BoGuu** [comment]
Then its a problem getting the config details for the TRYK clothing, but as you know, mods aren't supported, so you'll have to figure that one out yourself, it's not a build issue.
