### ISSUE TITLE
Housing Not working right.

### ISSUE THREAD

**Issue by torchgodz** [ArmaLife/Framework#741]
Hello everyone,

My community is having a problem with ARMA LIFE 4.4 when ever people buy houses everything works fine up until a server restart. After the restart they can spawn on said houses or garages but the house is not their so they have to rebuy it all over again. Just wondering if anyone else is having this problem thanks for your time and any help would be great thanks, and lets have some fun in Altis.

**Comment by BoGuu** [comment]
Are you referring to 4.4r2?

**Comment by torchgodz** [comment]
Oh sorry no 4.4r1, sorry for not defining which one.

**Comment by tkcjesse** [comment]
You should look at R2. This is fixed currently.
