### ISSUE TITLE
Can't stop escorting

### ISSUE THREAD

**Issue by AltisCityOwn** [ArmaLife/Framework#743]
Hey guys, 
In the cop's dialog, i've only the stop escorting action, for the moment, it's ok, but when i clic on the button ... nothing... the dialog disappears but action did'nt work :(

Anyone can help ?

**Comment by danielstuart14** [comment]
RPT Logs? (Client and server)

**Comment by AltisCityOwn** [comment]
Any "error in expression" in client/server logs

**Comment by tkcjesse** [comment]
Link the full logs please.

**Comment by AltisCityOwn** [comment]
server : http://pastebin.com/Wi4J40ab
client : http://pastebin.com/e6f56dQp

**Comment by danielstuart14** [comment]
Are you using the latest files?  This seems to be a bug from older versions.

**Comment by tkcjesse** [comment]
Pretty sure this is an old version and he has mods too as well as tons of strings listed twice in his string table. God only knows whats been changed.

**Comment by BoGuu** [comment]
You have countless issues and pretty much unreadable logs (to solve this problem with ease). Disable your mods and then paste the logs if you still have an issue, we are not detectives.
