### ISSUE TITLE
Database, ppl spawning without items, playtime, civ_position errors

### ISSUE THREAD

**Issue by Shinier** [ArmaLife/Framework#750]
Everytime i connect to server my character is naked without food and water filled up. After i die my character gets back to normal but it has no money that i had b4 i left server. playtime function seems to be broken too

Seems like my server is trying to get civ_position out of my database that is not having it. Same with playtime.

extdb2 config: http://pastebin.com/88k7wyq4
RPT log: http://pastebin.com/DbiymSrN
extdb2 log: http://pastebin.com/6RbDnWy1
Database structure: http://scr.hu/2vbh/js52t
there is a UID primary key on the top

**Comment by BoGuu** [comment]
The playtime function is broken in the last release unfortunately. To begin with, you can try removing it, or applying the fix here: https://github.com/ArmaLife/Framework/pull/613/files

**Comment by tkcjesse** [comment]
So are we good to close this?
