### ISSUE TITLE
about alive car and garage car limit

### ISSUE THREAD

**Issue by berkaslan** [ArmaLife/Framework#756]
Hey, 
I saw here an issuses about garage limit, why you can not try like this ;
When player spawned 2 or 3 car on server, 3th car can not spawn anytime need to put to garage to there cars.. is that possible :+1:  or impossible :-1: 

That will better for server performance allready. isnt :)

**Comment by DardoTheMaster** [comment]
We are working on it,thanks for the suggestion !

**Comment by tkcjesse** [comment]
Just have to do a life_vehicles count and and omit houses.

**Comment by berkaslan** [comment]
haha thats pretty cool :+1:

**Comment by DardoTheMaster** [comment]
https://github.com/ArmaLife/Framework/pull/762 Take a look

**Comment by berkaslan** [comment]
i saw it :) will try soon thnx for #762
