### ISSUE TITLE
Bug on Clothing Store

### ISSUE THREAD

**Issue by berkaslan** [ArmaLife/Framework#759]
1 bug on clothing store ; When you are click to buy clothing they can buy free
how to work;
Click on Rebel Clothing and on the fast time you need to make it.
Clothing name : "Guerilla Suit"
Click on keyboard "G" and Fast to Space/F/Enter and you took it. I just put there first name Guerilla to ".Guerilla" with "."

Video here : https://www.youtube.com/watch?v=05LI2o4bAcQ

**Comment by Jawshy** [comment]
I see that you are using a customised version of the mission. Can you reproduce this issue on the current build?

**Comment by tkcjesse** [comment]
Did you attempt it Jawshy?

**Comment by berkaslan** [comment]
There video is old on v4.3.x 

But yesterday i tried to check it on 4.4r2 - BASIC not added anything*, thist glitch works perfect :dancer:

**Comment by Jawshy** [comment]
I cannot reproduce this issue on the current build, even when using keyboard macros to activate the keys faster than a human could press them.

**Comment by berkaslan** [comment]
Players are working to find a glitch :dancers:
