### ISSUE TITLE
Car Shop/Rebel Shop - Different price with license...

### ISSUE THREAD

**Issue by berkaslan** [ArmaLife/Framework#764]
Hi, 

I would like to make a different price for license with car shop...
For Taxi license need to be different and also different price for rebel car shop

How can I fix it?

in config_master. files ;
`
vehicle_purchase_multiplier_CIVILIAN = 1; //Civilian Vehicle Buy Price = Config_Vehicle price * multiplier
    vehicle_purchase_multiplier_COP = .5; //Cop Vehicle Buy Price = Config_Vehicle price * multiplier
    vehicle_purchase_multiplier_MEDIC = .75; //Medic Vehicle Buy Price = Config_Vehicle price * multiplier
    vehicle_purchase_multiplier_OPFOR = -1; // -- NOT IN USE -- Simply left in for east support.
`

in Config_vehicle ;

class taxi {
        side = "taxi";
        vehicles[] = {
            { "C_SUV_01_F", { "", "", -1 } }

        };
    };

class C_SUV_01_F {
        vItemSpace = 50;
        licenses[] = { {"driver"}, {""}, {""}, {""} };
        price = 30000; --->>>ONLY 1 PRICE? I NEED TO MAKE license_civ_taxi different price to here! How? :)
        textures[] = {
            { "taxiı", "taxi", {
	                "\a3\soft_f_gamma\SUV_01\Data\suv_01_ext_co.paa"
            } },
           { "Turuncu", "civ", {
	                "\a3\soft_f_gamma\SUV_01\Data\suv_01_ext_04_co.paa"
        	} }
        };
    };

**Comment by berkaslan** [comment]
class taxi {
        side = "civ";
        vehicles[] = {
            { "C_SUV_01_F", 100000, { "driver" }, { "", "", -1 } },
            { "C_Hatchback_01_sport_F", 240000, { "driver" }, { "", "", -1 } }
        };
    };

There on 4.3x version was wworking perfect :+1:

**Comment by SalihF7** [comment]
http://hastebin.com/keciluhibe.m
buradaki oluşturduğum if yapısındaki gibi diğer satış ve marketi ilgilendiren dosyalara uygularsan farklı fiyat uyarlaması yapabilirsin. Tam olarak test etmedim fakat mantıken olması muhtemel
@Jawshy

**Comment by BoGuu** [comment]
This is coming back, fear not

**Comment by berkaslan** [comment]
@SalihF7 - side komutu ile cekmissin life_donor veya diger sekilde, license komutu ile farkli bir sekilde duzenlenmesi gerek :+1: 
mantiksal olarak Lisans aldiginda degil lvl eklendiginde gecerli olan bir sistem 
Side CIV/MED/WEST/EAST + DON

@Boguu i cant wait :palm_tree:

**Comment by SalihF7** [comment]
@berkaslan if(license_civ_taksi) then { }; aynen değiştirilmesi gerekiyor. boguu dediğine göre eski sisteme dönülecekmiş zaten yakında kolay gelsin

**Comment by berkaslan** [comment]
@SalihF7 aynen bu sistem guzel ayarli, fakat dengesiz :+1:

**Comment by BoGuu** [comment]
English please

**Comment by Jawshy** [comment]
@SalihF7, what does this have to do with me?
