### ISSUE TITLE
altislife SQL files

### ISSUE THREAD

**Issue by AltisCityOwn** [ArmaLife/Framework#766]
Hey
When i execute the request for add all DB with heidi SQL i got this error (check attached files).
Someone help me ?

Thanks ..

![2ad0c9f734ab93281b6ec4ff74412292](https://cloud.githubusercontent.com/assets/19275322/15635904/cb818780-25ed-11e6-931f-a6df7f621bc9.png)

**Comment by tkcjesse** [comment]
This is meant for repository issues. This is a "personal" issue if you would. Use gitter or altisliferpg.com for your support needs.

However it has to do with the support for whatever SQL version you are using... Make sure you're using the latest version of SQL to support timestamp & utf8mb4.
