### ISSUE TITLE
Wantedlist gets reset

### ISSUE THREAD

**Issue by Felix2** [ArmaLife/Framework#768]
When somebody gets added to the wantedlist and the server restarts the person doesn't show up in the wantedlist anymore.

Also people seem to be removed from the list when they respawn.

It's still there in the database but doesn't show up for the cops.

**Comment by tkcjesse** [comment]
This is on the current repo....?

**Comment by Felix2** [comment]
Yes, as far as i know it hasn't been fixed the pasta few weeks

**Comment by tkcjesse** [comment]
Well hasn't been fixed because it was never brought up. I'm attempting to validate this right now.

**Comment by tshowler1** [comment]
On my server with current repo from 1 week ago, the players are back on the wanted after restart, or after they've left?

**Comment by tkcjesse** [comment]
@BoGuu and I just tested this. We had no issues. We had the wanted player respawn, die, get manual charges, automatic charges. Restart the server. All worked fine.

**Comment by Felix2** [comment]
I have the devbranch from 3 weeks ago and I cant find any commit that fixes  this the past few weeks.

**Comment by tkcjesse** [comment]
As I said we tested it multiple variations and couldn't reproduce this. Please ensure you're using the VANILLA github repo without any modifications. Then please post the client / server RPT logs if you're still having the issue. I & BoGuu were unable to reproduce this issue.

**Comment by Felix2** [comment]
I will update my life_server files and check. I can see that the files have been updated a week ago but there was no commit.

I noticed that the == has been replaced by isEqualTo in fn_wantedFetch.sqf

**Comment by tkcjesse** [comment]
I really think the question is less of what we've done and more of what have you done? Did you add stuff? Are you using the basic files without any customization? Is your DB setup properly? Did you get DB install errors? What version of extDB are you using? etc.

**Comment by Felix2** [comment]
I haven't edited anything regarding the wantedlist or in the life_server. I have only edited stuff in the mission.sqm 

Im using extDB2 and there wasn't any install problems when installing except for a minor problem with the last_seen column in the players table.
