### ISSUE TITLE
Player get's resettet

### ISSUE THREAD

**Issue by Zeeanq** [ArmaLife/Framework#776]
My players having this issue.

If they arent playing for a few days (normaly 2-3 days) they are getting a reset.

Why is this hapening?

**Comment by sargken** [comment]
It could be a lot of things.

**Comment by sargken** [comment]
https://gitter.im/ArmaLife/Framework/Support?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by Zeeanq** [comment]
I know. Im there too. But the problem is .. Not every player gets this problem.

**Comment by BoGuu** [comment]
What does this reset entail, are their DB rows reset?

**Comment by Zeeanq** [comment]
i dont know. .. should i post you my rpt- extdb- or other logs

**Comment by danielstuart14** [comment]
that's not related to our framework. Probably, your database is corrupted, or maybe, your server is overloaded.

There's any string that deletes a player from database, in our code.

Attach all the RPT's. (Client (That'd been deleted), server (from these 2-3 days), and extdb logs (also from these 2-3 days).
