### ISSUE TITLE
Display Cash

### ISSUE THREAD

**Issue by AlaskaVet** [ArmaLife/Framework#778]
Maybe I did something but I don't think it was me. When I take money from my bank it wont show the cash I have in my hand. y menu and status bar are bot at 0$ even tho I have money in my hand.

**Comment by AlaskaVet** [comment]
So the issue seems to be this __CUR_MP.Altis\scripts\fn_statusBar.sqf, line 39
23:29:56 Error in expression <life_atmbank] call life_fnc_numberText,[life_cash] call life_fnc_numberText]; also  Error Undefined variable in expression: life_cash
23:29:56 File mpmissions\__CUR_MP.Altis\core\shops\fn_atmMenu.sqf, line 23 But I haven't touched the atm file so no clue why it's doing that.

**Comment by Jawshy** [comment]
Hi, @AlaskaVet. I did not encounter this issue in the [latest build](https://github.com/ArmaLife/Framework/tree/fb149c892f4199fad0a360403d5c047994bf7db0). 

As you seem to be using a custom build I will have to close this issue as GitHub Issues are only for the latest, vanilla build. For help with custom missions, please use the [support chat-room on Gitter](https://gitter.im/ArmaLife/Framework/Support), our [Discord server](https://discordapp.com/invite/0z4k0hcAcvMl2SQx), or post on the [Altis Life RPG Forums](http://www.altisliferpg.com/).
