### ISSUE TITLE
Framework Wiki for Spyglass.

### ISSUE THREAD

**Issue by berkaslan** [ArmaLife/Framework#779]
There I saw BFilter and more but not info for spyglass,

Please write a subject on wiki for config_spyglass. That will help us to learn it :)

**Comment by BoGuu** [comment]
https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/SpyGlass/README.md

**Comment by berkaslan** [comment]
I know that just wanted for wiki. nmv thnx :+1:
