### ISSUE TITLE
Persistent Messages

### ISSUE THREAD

**Issue by GetSomePanda** [ArmaLife/Framework#784]
I made a function to save messages to the database and pull them out via the phone, by clicking messages.

Wondering if you guys would like me to add it and make a pull request.

https://github.com/GetSomePanda/Persistent-Messages-AL-4.4

**Comment by GetSomePanda** [comment]
https://embed.gyazo.com/0d40707e14980b5982718e69bcdbe96f.jpg

**Comment by berkaslan** [comment]
I saw on AL. thats great i will try a day:)
