### ISSUE TITLE
Disabled channels now re-enabled due to syntax change

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#789]
Prior to _Arma 3_ update [1.60](https://dev.arma3.com/post/spotrep-00056) the chat channels were disabled via the [disableChannels](https://community.bistudio.com/wiki/Description.ext#disableChannels) attribute in the mission's [description.ext](https://github.com/ArmaLife/Framework/blob/13db23b72c8e2068aa40806065bcfb39f8c37bcc/Altis_Life.Altis/description.ext#L1) file. It had the following syntax: 
```
disableChannels[] = {channelID<number>, channelID<number>...}; // old syntax
Example:  disableChannels[] = {0,1,2};
```

In _Arma 3_ version 1.60 and above, the syntax was changed to allow support for disabling either the text or VON channels, or both. The new syntax is: 

```
disableChannels[] = {{channelID<number>, disableChat<bool>, disableVoice<bool>},{channelID<number>, disableChat<bool>, disableVoice<bool>},...}; // new syntax
Example:  disableChannels[]={{0,true,true},{1,true,false}...};
```

**Comment by Jawshy** [comment]
Tried the following but it did not work. 
```
disableChannels[]={{0,false,false},{1,false,false},{2,false,false}};    // Disabled text and voice for global, side, and command channels.
```

**Comment by berkaslan** [comment]
There some problem on Arma 3 :)

**Comment by BoGuu** [comment]
To disable would be true, not false

**Comment by Jawshy** [comment]
Thanks. Another command does it the opposite way.
