### ISSUE TITLE
Trying to setup a new server with 4.4r3

### ISSUE THREAD

**Issue by torchgodz** [ArmaLife/Framework#791]
Ive been trying to setup a brand new server with the 4.4r3 server files and it cannot connect to the database. It runs through everything then stops when it trys to connect to the database it keeps say extDB2 connection failed. Any help would be great

"extDB2: Error with Database Connection"

[13:52:15:654663 --4:00] [Thread 3060] extDB2: No Config Option Found:
[13:52:32:746970 --4:00] [Thread 3060] extDB2: Stopping ...

That exactly what the RPT and extDB RPTs are saying

**Comment by GetSomePanda** [comment]
Paste the extdb-conf.ini
In your extDB folder.

**Comment by torchgodz** [comment]
[Main]
Version = 5

;Threads = 0  
; Default Value is the number of CPU Cores Detected (max value is 6, min value is 2)

Randomize Config File = false
;This is a legacy option to randomize config file for Arma2 Servers. Only for Windows Builds


[Rcon]
;; This is functional, should be working fine. Just needs abit of testing on a $
;; Allow for changing Address for those running server in a VM environment.
IP = 127.0.0.1
Port = 2302

;; Rcon Password i.e Battleye/beserver.cfg
Password = 8675309867

;; Bad Player Name Checks
;;		This will only work if your mission / mod has started extDB2 Rcon. i.e 9:START_RCON:RCON
Bad Playername Enable = false
Bad Playername Kick Message = Bad Player Name

;; By default : is a bad character (used as seperator for extDB2 Calls (this is hardcoded in)
;;Bad Playername Strings = (:):{:}
;;Bad Playername Regex_1 = [:alnum:]
;;Bad Playername Regex_2 = [:alnum:]
;;Bad Playername Regex_3 = [:alnum:]


;; Whitelisting / Reserve Slots
;;		This will only work if your mission / mod has started extDB2 Rcon. i.e 9:START_RCON:RCON
Whitelist Enable = false
Whitelist Kick Message = Only Reserved Slots Left

Whitelist Public Slots = 999

;; Database settings to use (Optional)
Whitelist Database = MySQL_Example
Whitelist SQL Prepared Statement = SELECT CASE WHEN EXISTS(SELECT UID FROM PlayerInfo WHERE BattlEyeGUID=? AND Whitelisted=1) THEN 1 ELSE 0 END
Whitelist Kick on SQL Query Failed = false

;; Hardcoded BEGuids for whitelisted players
;Whitelist BEGuids = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx : yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy


[Steam]
;; This is for VAC Protocol for VAC Bans + Steam Friends.
;; https://steamcommunity.com/dev/apikey
API Key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


[VAC]
;; This feature requires Steam + Rcon to be enabled.
;; Also this feature is called via SQF Code atm, i.e it doesn't auto detect players joining server yet....
Auto Ban = true

;; For Player to get banned ( their total VAC Bans => NumberOfVACBans)  AND ( Days Since their Last Ban was <= DaysSinceLastBan)
;; This is also used extDB Protocol VAC:VACBanned returned results

NumberOfVACBans = 1
DaysSinceLastBan = 999999999
BanDuration = 0
;; 0 = Forever, otherwise its x Minutes
BanMessage = Steam VAC Banned


[Log]
;; Flush Logs after each write, more work on Harddrive
Flush = true


[altislife]
Type = MySQL
Name = altislife

Username = root
Password = ******

IP = 127.0.0.1
Port = 3306

;minSessions = 2
idleTime = 60

compress = false
; Really should only use this if MySQL server is external. Also only for MySQL

Secure Auth = true
; Recommend you turn this on  http://dev.mysql.com/doc/refman/5.6/en/mysql-command-options.html#option_mysql_secure-auth

[SQLite_Example]
Type = SQLite
Name = sqlite.db

minSessions = 1
; minSession Default Value = 1

;maxSessions = 4
; maxSession Default Value = number of Main->Threads
; 	You really should leave this value alone
idleTime = 60
; idleTime no Default Value yet, needs to be defined.
; 	idleTime is the time before a database session is stopped if not used. 
;	If Database Sessions are greater than minSessions

**Comment by torchgodz** [comment]
Ok so i got the connection to the DB to work but i still get an error that is doesnt connect right and gives me this error - [19:12:39:538943 --4:00] [Thread 588] extDB2: SQL_RAW_V2: Error StatementException: MySQL: [MySQL]: [Comment]: mysql_stmt_prepare error	[mysql_stmt_error]: Unknown column 'donorlevel' in 'field list'	[mysql_stmt_errno]: 1054	[mysql_stmt_sqlstate]: 42S22	[statemnt]: SELECT playerid, name, cash, bankacc, adminlevel, donorlevel, cop_licenses, coplevel, cop_gear, blacklist, cop_stats, playtime FROM players WHERE playerid='76561198046500923'
[19:12:39:538973 --4:00] [Thread 588] extDB2: SQL_RAW_V2: Error StatementException: SQL: SELECT playerid, name, cash, bankacc, adminlevel, donorlevel, cop_licenses, coplevel, cop_gear, blacklist, cop_stats, playtime FROM players WHERE playerid='xxxxxxxxxxxxxxxxxxxxxxxxxxxx'

**Comment by BoGuu** [comment]
@torchgodz 

Use the correct SQL provided with 4.4r3. Also use Gitter or the ALRPG forums for more help. (Gitter link in readme)
