### ISSUE TITLE
SpyGlass Bug (life_canpay_bail)

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#794]
Although this is extremely unlikely due to the time frame, I've seen it pop it's head up twice now.

life_canpay_bail is defined for only a small period of time (https://github.com/ArmaLife/Framework/blob/ab91f85c9e099846bc5e73d947ba20325b9e4631/Altis_Life.Altis/core/civilian/fn_jailMe.sqf#L23-31). This means that the SpyGlass variable check, given the right time frame, will pick up life_canpay_bail in allVariables, then fail to identify it's type because it has been undefined, which in turn will kick a player and throw RPT errors, namely:

```
15:15:20 "Variable: life_canpay_bail is not allowed TYPE:  NS: MN"
15:15:20 Error in expression <: %1 is not allowed TYPE: %2 NS: MN",_x,_varType];
failMission "SpyGlass";
};
};>
15:15:20   Error position: <_varType];
failMission "SpyGlass";
};
};>
15:15:20   Error Undefined variable in expression: _vartype
15:15:20 File mpmissions\__CUR_MP.Altis\SpyGlass\fn_variableCheck.sqf, line 61
15:15:20 Error in expression <_x);
_find = _allowedVariables find [_x,_varType];
if (_find isEqualTo -1) then >
15:15:20   Error position: <_varType];
if (_find isEqualTo -1) then >
15:15:20   Error Undefined variable in expression: _vartype
15:15:20 File mpmissions\__CUR_MP.Altis\SpyGlass\fn_variableCheck.sqf, line 59
```

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Framework/pull/795

https://github.com/ArmaLife/Framework/pull/796

**Comment by tkcjesse** [comment]
@danielstuart14 you recent updates broke the pay bail.

https://github.com/ArmaLife/Framework/blob/bbc519c402ff0829c6d6414318d6f32c3146d6e1/Altis_Life.Altis/core/civilian/fn_jailMe.sqf#L36

`if (isNil "life_canpay_bail") then {"Yes"} else {"No"}];`

Now it's never nil, needs to be updated.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Framework/commit/b7e40474b73e5a9748583a08c35b0862adda7889
