### ISSUE TITLE
Tempest fuel bug

### ISSUE THREAD

**Issue by berkaslan** [ArmaLife/Framework#802]
Players are make tempest fuel 0 and still works and they makes more than.
if tempest capacity : 600 they are glitching to more than 1000 - 2000 - 3000 :/

**Comment by BoGuu** [comment]
Can you please make a video to explain, I am not following, and I'm sure other people are the same.

**Comment by DardoTheMaster** [comment]
Yep this bug is present since 3.1.x. 
Doing a clip.

**Comment by berkaslan** [comment]
There is a picture http://i.hizliresim.com/Zd7j4g.jpg

**Comment by berkaslan** [comment]
There is a video allready : When spent the fuel on tempest :+1: 
https://youtu.be/BWKU1sJCpsg?t=2m58s (video is not mine but all version is works fine :pager:

**Comment by BoGuu** [comment]
Which part of the video?

**Comment by GetSomePanda** [comment]
Are you sure this is an issue with the current version as there is a check to see if there is fuel to let them mine.

`if(fuel _vehicle == 0) exitWith {titleText[localize "STR_NOTF_OutOfFuel","PLAIN"];};`

I'm wondering because the video was from last year.

**Comment by berkaslan** [comment]
```
fn_deviceMine.sqf:
   80  	};
   81  	
   82: 	if(fuel _vehicle == 0) exitWith {titleText[localize "STR_NOTF_OutOfFuel","PLAIN"];};
   83  	
   84  	//Locality checks...
   ..
   89  	};
   90  	
   91: 	if(fuel _vehicle == 0) exitWith {titleText[localize "STR_NOTF_OutOfFuel","PLAIN"];};
   92  	titleText[format[localize "STR_NOTF_DeviceMined",_sum],"PLAIN"];
   93  	_vehicle SVAR ["Trunk",[_items,_space + _itemWeight],true];

2 matches in 1 file
```
check it :) allready I have this.

**Comment by GetSomePanda** [comment]
Yes but that check should stop people using the mine functions when there fuel is empty.

**Comment by berkaslan** [comment]
Normally yeap but it couldnt :dancers: Still works :|

**Comment by GetSomePanda** [comment]
@BoGuu Basically when the tempest device has no fuel and when you use the mine function it generates thousands of the resource it is mining.

**Comment by Chickenw** [comment]
I went into my server 4.4R3 and this bug is fixed. It stops mining when its out of fuel. Wont let u restart it. when the tank gets to 1/4 it stops the mining

**Comment by BoGuu** [comment]
@Chickenw 

What version is this? Is it the dev build?

**Comment by Chickenw** [comment]
Yes 4.4R3

**Comment by BoGuu** [comment]
I can see the problem in the script, will fix soon

**Comment by DardoTheMaster** [comment]
@BoGuu Just for curiosity,what is the problem ?

**Comment by BoGuu** [comment]
@DardoTheMaster 

It breaks out the loop at 111, then doesn't get broken out of the next loop before the items are added:

https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/core/vehicle/fn_deviceMine.sqf#L111-144
