### ISSUE TITLE
Weapons Save

### ISSUE THREAD

**Issue by Blitzzer63** [ArmaLife/Framework#806]
Hi everyone, today i'm here to tell you about one problem i've in my Altis Life server. It's about the weapons of civilians. When you disconnect, all the weapons you've disappear.Even if you've it in your backpack every weapons dissapear when you're reconnect even if in the serve file it's on ON position in Config_Master.hpp.

```
/* Persistent Settings */
    save_civ_weapons = true;
    save_virtualItems = true; 
    save_playerStats = true; 
    save_veh_virtualItems = true;
    save_veh_gear = true;
```

If someone have any solution i want it ^^
thx

**Comment by tshowler1** [comment]
Edit accordingly;

Save Civ Weapons: https://github.com/ArmaLife/Framework/search?utf8=%E2%9C%93&q=save_civilian_weapons
Save Virtual Items: https://github.com/ArmaLife/Framework/search?utf8=%E2%9C%93&q=save_virtualItems
Player Stats: https://github.com/ArmaLife/Framework/search?utf8=%E2%9C%93&q=save_playerStats
Save Vehicle Virtual Items: https://github.com/ArmaLife/Framework/search?utf8=%E2%9C%93&q=save_vehicle_virtualItems

Save Vehicle Gear? Not sure, what I posted above is what the var's are in 4.4R2 (No i dont want to change)
If you're running R3 change the var name and call it correctly.

**Comment by tkcjesse** [comment]
This doesn't appear to be an issue?

**Comment by tshowler1** [comment]
@tkcjesse Cross reference what he posted, to what they actually are.

Not sure how he ended up with something like what he posted. :/
