### ISSUE TITLE
Tempest Device Bug

### ISSUE THREAD

**Issue by SalihF7** [ArmaLife/Framework#818]
fn_deviceMine.sqf : http://hastebin.com/demobubuzo.coffee
fn_vInteractionMenu.sqf : http://hastebin.com/ebizihapud.coffee

Bug : 
`if (fuel _vehicle < 0.1) exitWith {
        _vehicle setVariable ["mining",nil,true];
        titleText[localize "STR_NOTF_OutOfFuel","PLAIN"];
    };`

gasoline finished and `if (typeOf _curTarget == "O_Truck_03_device_F") then {
        _Btn3 ctrlSetText localize "STR_vInAct_DeviceMine";
        _Btn3 buttonSetAction "[life_vInact_curTarget] spawn life_fnc_deviceMine";
        if (!isNil {(_curTarget getVariable "mining")} || !local _curTarget && {_curTarget in life_vehicles}) then {
            _Btn3 ctrlEnable false;
        } else {
            _Btn3 ctrlEnable true;
        };`

_Btn3 ctrlEnable true; ? 

You need closure gasoline finished gathering button

**Comment by tkcjesse** [comment]
Is this not the exact same issue as: https://github.com/ArmaLife/Framework/issues/802 ?

**Comment by SalihF7** [comment]
Yes same
