### ISSUE TITLE
Housing 

### ISSUE THREAD

**Issue by AltisCityOwn** [ArmaLife/Framework#819]
Hi, 

The housing system didn't work for me,
Can buy house, can put containers in my house, after a reboot, we can still buy my house and containers cant be used (windows action)

Maybe it's a general mission bug?
If it's mine, i'm sorry..

Sorry bad english ...
Thanks

**Comment by setoy** [comment]
What?

**Comment by AltisCityOwn** [comment]
Miss clic :D i've edit my 1st message

**Comment by Heavybob** [comment]
Post an RPT. Disregard the spyglass stuff, just follow these instructions. 
https://www.youtube.com/watch?v=RcALhFBWCKw&feature=youtu.be&t=28s

Then send the hastebin of the results. Do the same with server RPT.

**Comment by AltisCityOwn** [comment]
http://pastebin.com/hZyR8v03

Soory forget this, my bad,
i've found only this in my rpt, other is full " Error: Object(X : XX) not found

**Comment by AltisCityOwn** [comment]
Nanou give me solution

life_hc/fn_initHc.sqf

under
`[] spawn HC_fnc_cleanup;`
add this
`[] spawn HC_fnc_initHouse;`

Thanks

**Comment by BoGuu** [comment]
Welcome to the previously broken HC system. Glad you sorted it.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Framework/commit/a9a9cae1f55658d53ccae1397089279a37b24e02

**Comment by BoGuu** [comment]
@danielstuart14 

I fixed this already, please remove that commit, it'll just cause issues

**Comment by danielstuart14** [comment]
then, just commit it...

**Comment by BoGuu** [comment]
@danielstuart14 

This was fixed a long time ago. This issue is not related to the dev branches current status. Just talk to me on Gitter
