### ISSUE TITLE
Error on login Somtimes?

### ISSUE THREAD

**Issue by Chickenw** [ArmaLife/Framework#820]
Hello so every now and then i get this error. 
20:20:24 "::Life Client:: Initialization Variables"
20:20:24 Error in expression <rver_isReady","_extDB_notLoaded"];

"----------------------------------------------------------------------------------------------------"
20:20:24 "--------------------------------- Starting Altis Life Client Init ----------------------------------"
20:20:24 "------------------------------------------ Version 4.4R3 -------------------------------------------"
20:20:24 "----------------------------------------------------------------------------------------------------"
20:20:24 "::Life Client:: Initialization Variables"
20:20:24 Error in expression <rver_isReady","_extDB_notLoaded"];

if (life_HC_isActive) then {
_server_isReady>
20:20:24   Error position: <life_HC_isActive) then {
_server_isReady>
20:20:24   Error Undefined variable in expression: life_hc_isactive
20:20:24 File mpmissions\__CUR_MP.Altis\core\init.sqf, line 11
20:20:24 "::Life Client:: Variables initialized"
20:20:24 "::Life Client:: Setting up Eventhandlers"
20:20:24 "::Life Client:: Eventhandlers completed"
20:20:24 "::Life Client:: Setting up user actions"
20:20:24 "::Life Client:: User actions completed"
20:20:24 "::Life Client:: Waiting for server functions to transfer.."
20:20:24 "::Life Client:: Received server functions."
20:20:24 "::Life Client:: Waiting for the server to be ready.."

All i have to do is restart my Arma and it works.

**Comment by danielstuart14** [comment]
Can you check this?
https://github.com/ArmaLife/Framework/commit/8fb33511cd51ceca18dcfe8b76a7674e142959da

**Comment by Chickenw** [comment]
Okay tried it 4times already no errors it may take a day or 2 to see if it pops up again.

**Comment by danielstuart14** [comment]
okay, I'll close it. If you find any error, just post here and I'll reopen it.

**Comment by BoGuu** [comment]
I will rework this, as it's not really needed, I put some fail safe in there already

**Comment by Chickenw** [comment]
Just did this again but i was able to login

`11:20:09 Attempt to override final function - bis_fnc_endmission
11:20:09 Error in expression <life_server_isReady;
_extDB_notLoaded = life_server_extDB_notLoaded;
};

life_fi>
11:20:09   Error position: <life_server_extDB_notLoaded;
};

life_fi>
11:20:09   Error Undefined variable in expression: life_server_extdb_notloaded
11:20:09 File mpmissions\__CUR_MP.Altis\core\init.sqf, line 16
11:20:09 "----------------------------------------------------------------------------------------------------"
11:20:09 "--------------------------------- Starting Altis Life Client Init ----------------------------------"
11:20:09 "------------------------------------------ Version 4.4R3 -------------------------------------------"
11:20:09 "----------------------------------------------------------------------------------------------------"`

**Comment by BoGuu** [comment]
Yeh panic too much, I'll fix all this up shortly

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Framework/commit/d7c42d7b6dcd2a455257920f41262f05e78b3e91
