### ISSUE TITLE
Storagebox problem

### ISSUE THREAD

**Issue by Felix2** [ArmaLife/Framework#821]
When I place a storagebox inside a house it's not possible to store items inside it. When you abort and reconnect to the server it is possible to use the storagebox like normal though.

It's been tested on 1.62 & 1.63 and on Altis & Tanoa.  A person also told me that it effects the 1.60 version.

**Comment by BoGuu** [comment]
Can you test with https://github.com/ArmaLife/Framework/commit/d0b77d133324fd66ea15a63e5083c50b9cff6243 please

**Comment by Felix2** [comment]
I tested it and it solved the problem!
Thanks
