### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MegaDemik** [ArmaLife/Framework#823]
When I press the key combination Shift + Y, the texture of the phone appears. What is this for? Will it work?

**Comment by BoGuu** [comment]
It is for a WIP phone, it shouldn't really be activated in the keyhandler for releases, or even in them, but hey, it is. I'm sure you can answer the latter question yourself

**Comment by danielstuart14** [comment]
yeah, I forgot about it. Now, it's time to start working on it.
