### ISSUE TITLE
setPlaytime issue

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Framework#824]
15:53:18 "--------------------------------------------"
15:53:27 Error in expression <) isEqualTo _uid) exitWith {
_x set [1, _time_gathered];
_x set [2, time];
};
} >
15:53:27   Error position: <_time_gathered];
_x set [2, time];
};
} >
15:53:27   Error Undefined variable in expression: _time_gathered
15:53:27 File life_server\Functions\PlayTime\fn_setPlayTime.sqf, line 24
15:53:27 Error in expression <st pushBack [_uid, _new];
};
[_uid,_new select 2] call TON_fnc_setPlayTime;

_ho>
15:53:27   Error position: <select 2] call TON_fnc_setPlayTime;

_ho>
15:53:27   Error Zero divisor
15:53:27 File life_server\Functions\MySQL\fn_queryRequest.sqf, line 122

**Comment by tkcjesse** [comment]
this is the current vanilla repo?

**Comment by HyunsukBaek** [comment]
@tkcjesse  yes, it's vanilla.

**Comment by BoGuu** [comment]
4.4R3 onwards? Try reset your playtime columns, it is not broken.

**Comment by BoGuu** [comment]
Post here if you are using the latest build, and have reset your playtime column AND are still experiencing this.

**Comment by tkcjesse** [comment]
If you are indeed using latest build also post your RPT logs and such please.
