### ISSUE TITLE
extDB2 : "NoConfig Option Found:"

### ISSUE THREAD

**Issue by JohnConry** [ArmaLife/Framework#825]
Hello, 

I apologize to post here, but i seen extDB2's github is not currently supported (i guess).. So i have a problem, when i'm running my server, i got this error : http://hastebin.com/igoligexul.avrasm
But i dont know, where i can find this config, and where i need to put it on ...
Thanks for answers, and once again, sorry for posting here.. for an external problem at ArmaLife.

Sincerely.

**Comment by BoGuu** [comment]
Please use the Gitter or ALRPG forums for help with this, it is not an issue on the repo.

However, verify your DB name is correct in relevant files.
