### ISSUE TITLE
HC fn_spawnVehicle.sqf

### ISSUE THREAD

**Issue by asremix** [ArmaLife/Framework#827]
`16:54:36 Error in expression < isEqualTo "") exitWith {};
if (_vid in serv_sv_use) exitWith {};
serv_sv_use pu>
16:54:36   Error position: <serv_sv_use) exitWith {};
serv_sv_use pu>
16:54:36   Error Undefined variable in expression: serv_sv_use
16:54:36 File life_hc\MySQL\Vehicles\fn_spawnVehicle.sqf, line 28
16:54:36 Error in expression <ecCall ["life_fnc_broadcast",_unit];
};
serv_sv_use deleteAt _servIndex;

>
16:54:36   Error position: <serv_sv_use deleteAt _servIndex;

>
16:54:36   Error Undefined variable in expression: serv_sv_use
16:54:36 File life_hc\MySQL\Vehicles\fn_spawnVehicle.sqf, line 183`

**Comment by danielstuart14** [comment]
It should fix: https://github.com/ArmaLife/Framework/commit/36f13858c651db40ec2d18fe492e18d45b6b5a3f

Test and give a feedback, pls.
