### ISSUE TITLE
Debug Console

### ISSUE THREAD

**Issue by JohnConry** [ArmaLife/Framework#830]
Hello,

Is that normal, if the debug console, available from "phone (Y) -Admins - Debug Console" doesn't work ? 
I write down some basic command, and nothings happens..

**Comment by gouglhupf** [comment]
Same problem. The server log says that local commands are not allowed, but I don't know how to allow them again.

**Comment by tkcjesse** [comment]
Put 'call' in the functions section of cfgremoteexec

**Comment by Jawshy** [comment]
`F(call,ANYONE)` needs to go under `class Commands` not `class Functions` in [CfgRemoteExec.hpp](https://github.com/ArmaLife/Framework/blob/87eea05ab2cd6e5d3d59197d15c717bf8f32671d/Altis_Life.Altis/CfgRemoteExec.hpp#L164-L173).

**Comment by tkcjesse** [comment]
^ yeh responded from my phone as i was leaving work. Couldn't remember what one it was. Had a 50% chance of being right.
