### ISSUE TITLE
tag error 

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Framework#838]
2:26:59 Attempt to override final function - rscunitinfo_script
 2:27:00 Initializing Steam server - Game Port: 2302, Steam Query Port: 2303
 2:27:00 Steam AppId in current environment: 107410
 2:27:02 Connected to Steam servers
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' Lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unsupported language English in stringtable
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' Lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unknown entity: ' lt'
 2:27:04 Unknown entity: ' gt'
 2:27:04 Unsupported language English in stringtable
 2:27:04 Altis Life RPG v4.4r3: string @STR_MISC_overviewText cannot be localized client-side - move to global stringtable

1. plz delete space before lt, gt tags  in stringtable
2. can't find @STR_MISC_overviewText

**Comment by Jawshy** [comment]
@HyunsukBaek, please test with https://github.com/ArmaLife/Framework/pull/839.
