### ISSUE TITLE
[COP] Confiscation Issue

### ISSUE THREAD

**Issue by Latouth** [ArmaLife/Framework#842]
When you play as a cop, and you have spikestrips and a rebel kills you.
The spikestrips drop,
Then when you go back to pick them up, you take them as evidence but the menu says the stringtable localization name, not "Spikestrips" so it says like "STR_Item_SpikeStrip was taken into evidence" or w/e the message is.

**Comment by Heavybob** [comment]
if (playerSide == west) then {
*fn_spikestrip.sqf bullshit script*
} else {
exitWith {};

Go team. Make it so.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Framework/commit/33ba5cc3cbdd6fa3143c6049a6ff2a0359c0e275
Should fix
