### ISSUE TITLE
fn_buyLicense false parameter

### ISSUE THREAD

**Issue by donarfr** [ArmaLife/Framework#856]
the function buyLicense  passes_varName and _sideFlag to the Marcro LICENSE_VARNAME.
`_varName = LICENSE_VARNAME(_varName,_sideFlag);`

But the macro itself gets the  variable name from the config.

`#define LICENSE_VARNAME(varName,flag) format["license_%1_%2",flag,M_CONFIG(getText,"Licenses",varName,"variable")]`

If the class name and the variable name are equal it has no effect, but if they are not equal the license name is generated wrong.

to fix this change line 17 to

`_varName = LICENSE_VARNAME(_type,_sideFlag);`

and delete line 13

**Comment by Jawshy** [comment]
Would you like to make a [pull request](https://help.github.com/articles/creating-a-pull-request/)?
