### ISSUE TITLE
Police cannot see markers of dead players

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#860]
Medics/EMS can see the location and name of players that are in need of reviving. Police cannot see this and yet they are expected to be able to handle medic requests when no medics are online. 

##### Relevant files: 
* [Framework/Altis_Life.Altis/core/cop/fn_copMarkers.sqf](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/core/cop/fn_copMarkers.sqf) 
* [Framework/Altis_Life.Altis/core/medical/fn_medicMarkers.sqf](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/core/medical/fn_medicMarkers.sqf) 

----

Mission version: 4.4r3

**Comment by HyunsukBaek** [comment]
yes

**Comment by DarkSilencerZA** [comment]
This is very true good sir.
