### ISSUE TITLE
Capturing hideout shows %NaN

### ISSUE THREAD

**Issue by setoy** [ArmaLife/Framework#874]
Capturing a hideout shows "Capturing hideout (%NaN)" in the progress bar

Reproducible with repository mission file

**Comment by BoGuu** [comment]
Are you using Tanoa?

**Comment by CarlosHingel** [comment]
He said "Reproducible with repository mission file", so i suppose he is using a vanilla version, in other words, altis and etc.

**Comment by BoGuu** [comment]
Indeed, but the 'vanilla version' can be converted to Tanoa with a simple rename, and it seems *almost* everybody is attempting it. This error would also go hand in hand with that.

**Comment by CarlosHingel** [comment]
Yeah...

**Comment by setoy** [comment]
Yes, I'm using Tanoa.

**Comment by setoy** [comment]
Any explanation on why this obvious bug was closed?

**Comment by BoGuu** [comment]
Check the flagpole code relating to buildings. When the Tanoa build is out, feel free to makes issues and ask questions, but these currently do **not** relate to the repo - Altis.

**Comment by CarlosHingel** [comment]
The explanation why it was close is pretty clear "using Tanoa".

**Comment by NiiRoZz** [comment]
@setoy look inside fn_captureHideout, in line 10 : 
``` _hideout = (nearestObjects[ASLtoATL (getPosASL player),["Land_u_Barracks_V2_F","Land_i_Barracks_V2_F"],25]) select 0; ```

Script search houses of Altis, just change classname with house proximity of your hideout

**Comment by setoy** [comment]
Thanks!

**Comment by NiiRoZz** [comment]
No problem
