### ISSUE TITLE
life_server\init.sqf line 84 bank_obj

### ISSUE THREAD

**Issue by GamesTrap** [ArmaLife/Framework#876]
Hey i'm getting this issue every time my server starts:

"----------------------------------------------------------------------------------------------------"

"---------------------------------- Starting Altis Life Server Init ---------------------------------"
"------------------------------------------ Version 4.4R3 -------------------------------------------"
"----------------------------------------------------------------------------------------------------"
Error in expression <syncCall;
};
};

master_group attachTo[bank_obj,[0,0,0]];

{
_hs = createVehicl>
  Error position: <bank_obj,[0,0,0]];

{
_hs = createVehicl>
  Error Undefined variable in expression: bank_obj
File life_server\init.sqf, line 84
"----------------------------------------------------------------------------------------------------"
"               End of Altis Life Server Init :: Total Execution Time 0.0669975 seconds "
"----------------------------------------------------------------------------------------------------"

**Comment by BoGuu** [comment]
Tanoa..?

**Comment by GamesTrap** [comment]
yes

**Comment by gouglhupf** [comment]
It tries to attach the "bank_obj" object from the misson to the master group, but there is no such object. 
So just add in the mission editor an object with the var_name "bank_obj" (I dont remember the classname of the original item, but it shouldnt matter).
Anyway I would add an if-cause for this part of the script to prevent this from happening to other server owners.

**Comment by GamesTrap** [comment]
thx i will try that

**Comment by GamesTrap** [comment]
thx it worked u can close this issue
