### ISSUE TITLE
Side switch Blackscreen

### ISSUE THREAD

**Issue by GamesTrap** [ArmaLife/Framework#878]
Hey, if im logged in as civilian and then logout and switch the side to a cop slot and login back then i get a blackscreen where normally the spawn menu is. i can move myself on the spawn island but cant see myself because of the blackscreen. i only changed Altis_Life.Altis to Tanoa_Life.Tanoa.
[arma3server_2016-07-14_17-50-37.txt](https://github.com/ArmaLife/Framework/files/364229/arma3server_2016-07-14_17-50-37.txt)

**Comment by BoGuu** [comment]
Wait until a Tanoa build is out, or use the forums, discord etc.

**Comment by GamesTrap** [comment]
i setup a complete new server with vanilla Altis_Life.Altis and a complete fresh database but still get the same bug on switching from civilian to a public cop slot.
[arma3server_2016-07-14_20-12-56.txt](https://github.com/ArmaLife/Framework/files/364501/arma3server_2016-07-14_20-12-56.txt)

**Comment by GamesTrap** [comment]
Nevermind solved it persistent was 0 xD
