### ISSUE TITLE
Error MySql 1293 

### ISSUE THREAD

**Issue by Thesam1798** [ArmaLife/Framework#888]
#1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause 

correctif ligne :

95 :   'insert_time' timestamp NOT NULL DEFAULT 0 ,
96 :  'last_seen' timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

on altislife.sql

**Comment by tkcjesse** [comment]
Update your sql to the newest version... this is like duplicate issue number 100...
