### ISSUE TITLE
fn_wanted person uid bug

### ISSUE THREAD

**Issue by ColinM9991** [ArmaLife/Framework#894]
https://github.com/ArmaLife/Framework/blame/adbe536ab41dff6d58b1b5e61b659ce49938fd19/life_server/Functions/WantedSystem/fn_wantedPerson.sqf#L14

Line 14

No need in even pointing out why that's wrong, that certainly wasn't in my original.

**Comment by BoGuu** [comment]
Is it broken? You've said bug

**Comment by Sakzy** [comment]
Also you can not understand why the person is sought in the wanted list ?
I can see the person in the wantelist but can not see the reason of the research ...

**Comment by tkcjesse** [comment]
What... @Sakzy

**Comment by dbenson24** [comment]
@tkcjesse He says he can't see the list of charges for a person, only the number they are wanted for

**Comment by ColinM9991** [comment]
I haven't tested, but I know it won't work as it should

It's executed on the server, the server is not a player and has no uid, it
should be getting the Id of the _unit

On 25 Jul 2016 22:21, "BoGuu" <notifications@github.com> wrote:

Is it broken? You've said bug

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArmaLife/Framework/issues/894#issuecomment-235089239>,
or mute the thread

**Comment by BoGuu** [comment]
I failed to see the player reference at first sight, was focused on the use of getPlayerUID. It is indeed an issue, but will have gone unnoticed due to the lack of need for a non-zero element array over at the bail stuff.

**Comment by ColinM9991** [comment]
It's only used in the jailSys file one time

**Comment by BoGuu** [comment]
Yep, and continues regardless if the crimes array is empty, so nobody noticed! Good spot :+1:

**Comment by ColinM9991** [comment]
For Sakzy's benefit, crimes are loaded when you select an individual in the list, if I remember correctly.

If you see no crimes then you should be checking client and server logs. If that's an issue many have had, then I'd say there were problems with the initial migration of the persistent wanted system.

Back when I made it, I had little actual programming knowledge. Now that I have expanded that knowledge, I will revisit the system and improve it all some day.

**Comment by Sakzy** [comment]
Where we can find the file sql_custom_v2 for this mpmission please ?

**Comment by Jawshy** [comment]
Closing as https://github.com/ArmaLife/Framework/pull/898 fixed the issue.
