### ISSUE TITLE
fn_bool.sqf Update  NiiRoZz Error

### ISSUE THREAD

**Issue by Mateuus** [ArmaLife/Framework#900]
private["_bool","_mode"];
params [
["_bool",0,[false,0]],
["_multi>
 5:05:30   Error position: <params [
["_bool",0,[false,0]],
["_multi>
 5:05:30   Error Params: Type Array, expected Number,Bool
 5:05:30 File life_server\Functions\MySQL\fn_bool.sqf, line 10

Fix fn_bool.sqf

params [
["_bool",0,[false,0]],
["_mode",0,[0]]
];

**Comment by Jawshy** [comment]
Could you please reference the offending commit or pull request? 

Was that error found in the server or client/local.rpt log file? I'm assuming server.rpt.

**Comment by tkcjesse** [comment]
gee, an error with the PARAM pull... Maybe we should've tested it....

@danielstuart14

**Comment by Mateuus** [comment]
Fix fn_bool.sqf

`params [
 +   ["_bool",0,[false,0]],
 +   ["_mode",0,[0]]
  ];`
it was just a typo maybe

**Comment by Jawshy** [comment]
@tkcjesse, are you saying that the Travis CI checks aren't infallible? \*gasp*

**Comment by tkcjesse** [comment]
Hah.
