### ISSUE TITLE
Warning Message: Script not found

### ISSUE THREAD

**Issue by SAYREXx** [ArmaLife/Framework#903]
16:11:05 Warning Message: Script core\vAH\fn_vAH_load.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_buy.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_reciever.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_loadInventory.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_sell.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_checkItem.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_takeBack.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_select.sqf not found

**Comment by Jawshy** [comment]
Those warning messages have nothing to do with this repository or the Altis Life RPG mission.

**Comment by SAYREXx** [comment]
[arma3server_2016-07-31_16-24-26.txt](https://github.com/ArmaLife/Framework/files/392304/arma3server_2016-07-31_16-24-26.txt)

**Comment by SAYREXx** [comment]
Decided error. Thank you!
