### ISSUE TITLE
Missing Something?

### ISSUE THREAD

**Issue by EagleonePrimo** [ArmaLife/Framework#906]
File -> life_server/Functions/MySQL/fn_updateRequest.sqf

i thing you miss "private ["_ex1","_ex1"];"

it make server don't save data after i'm disconnect

I do not sure But when I added it It was back to work

if you not understand i'm so sorry my english skill is so bad

**Comment by BoGuu** [comment]
I'm not sure why you feel adding that helps anything. For a start _ex1 is not even a variable. I'm going to close this. If this 'fixed' it for you, then you had a different problem.

**Comment by EagleonePrimo** [comment]
this variable look look like this
`private["_user","_uid","_side","_cash","_bank","_licenses","_gear","_stats","_name","_position","_query"];`

**Comment by BoGuu** [comment]
Most of them are already private (except playtime), but this is **not** something that should be breaking your updates

**Comment by tkcjesse** [comment]
I don't think that file has been modified recently to make an issue like this either.
