### ISSUE TITLE
"BIS_fnc_param -> Param" update, does not save Item & ETC

### ISSUE THREAD

**Issue by magicianaos** [ArmaLife/Framework#907]
after BIS_fnc_param update.

Every item's & license & gear does not save DB.

My test server client vanilla version.

Please check the ploblem.

**Comment by coresync2k** [comment]
yes you are right, i have the same issue, i reworked my updaterequest.sqf on life_server and it saves Licenses and gear

**Comment by NiiRoZz** [comment]
Please, you can add any rpt inside your issue ?

**Comment by nearbyplayer** [comment]
I happen to have a similar issue, licenses don't save to the database (at all) even though everything else saves. There aren't any errors that I could locate either (I've looked).

**Comment by coresync2k** [comment]
rpt logs say no error. thats why so stupid. i reworked my updaterequest.sqf and it works

**Comment by nearbyplayer** [comment]
@coresync2k Are you willing to explain how you did that?

**Comment by coresync2k** [comment]
sorry, ich only used the "old" param 

`private["_uid","_side","_cash","_bank","_licenses","_gear","_stats","_name","_alive","_position","_query","_thread"];
_uid = [_this,0,"",[""]] call BIS_fnc_param;
_name = [_this,1,"",[""]] call BIS_fnc_param;
_side = [_this,2,sideUnknown,[civilian]] call BIS_fnc_param;
_cash = [_this,3,0,[0]] call BIS_fnc_param;
_bank = [_this,4,5000,[0]] call BIS_fnc_param;
_licenses = [_this,5,[],[[]]] call BIS_fnc_param;
_gear = [_this,6,[],[[]]] call BIS_fnc_param;
_stats = [_this,7,[100,100],[[]]] call BIS_fnc_param;
_alive = [_this,9,0,[0]] call BIS_fnc_param;
_position = [_this,10,[],[[]]] call BIS_fnc_param;`

**Comment by magicianaos** [comment]
@coresync2k  Old "fn_updaterequest.sqf" is work fine.

**Comment by coresync2k** [comment]
thats the old updaterequest

**Comment by NiiRoZz** [comment]
You use Headless Client ?

**Comment by coresync2k** [comment]
nope, i dont use a HC

**Comment by NiiRoZz** [comment]
Test with #909 please

**Comment by coresync2k** [comment]
i will try it in a few minutes on my dev server

**Comment by coresync2k** [comment]
i test it, and it dont work i have a extDB2 log for you

[12:34:01:900846 +02:00] [Thread 6844] extDB2: Invalid Format: 1:60627:
[12:34:17:382732 +02:00] [Thread 6844] extDB2: Invalid Format: 1:60627:
[12:34:22:002996 +02:00] [Thread 6844] extDB2: Invalid Format: 1:60627:

no error in server,rpt or client.rpt

**Comment by BoGuu** [comment]
@coresync2k 

Use the debug .dll (https://github.com/ArmaLife/extDB2/releases), then post your log.

**Comment by coresync2k** [comment]
here is the extdb2 log with debug.dll
[extdb2.txt](https://github.com/ArmaLife/Framework/files/401430/extdb2.txt)

**Comment by NiiRoZz** [comment]
Test with last commit of #909 please

**Comment by coresync2k** [comment]
i tryed with the new one, but i dont work -> all licenses in the Databse are now 0

here is the new extdb2 debug log. i tryed with #909
[extdb2.txt](https://github.com/ArmaLife/Framework/files/401465/extdb2.txt)

**Comment by NiiRoZz** [comment]
Gear work ?

**Comment by coresync2k** [comment]
oh very sorry false database entry, licenses are not 0. but not updated and gear are not saved.

**Comment by NiiRoZz** [comment]
Position update for civilian ?

**Comment by coresync2k** [comment]
deactivated

**Comment by NiiRoZz** [comment]
No logs inside server.rpt ?

**Comment by coresync2k** [comment]
sure i have logs, but no errors :D

**Comment by NiiRoZz** [comment]
Stats of player updated ?

**Comment by coresync2k** [comment]
yes

**Comment by NiiRoZz** [comment]
Test with the new last commit please

**Comment by coresync2k** [comment]
no gear save, no license save, and no stat save.
[extdb2.txt](https://github.com/ArmaLife/Framework/files/401521/extdb2.txt)

**Comment by NiiRoZz** [comment]
Test with last commit

**Comment by coresync2k** [comment]
i m sorry, to tell you, it is not working.
[extdb2.txt](https://github.com/ArmaLife/Framework/files/401584/extdb2.txt)

**Comment by NiiRoZz** [comment]
Stats update ?

**Comment by coresync2k** [comment]
no lic/gear/stats

**Comment by NiiRoZz** [comment]
you can send me server.rpt please

**Comment by coresync2k** [comment]
there are NO Server.RPT errors, i use now the "old" fn_updatereqeust.sqf" 
and and NEW extdb2 debug log with the updaterequest.

https://github.com/AsYetUntitled/Framework/blob/master/life_server/Functions/MySQL/fn_updateRequest.sqf

[extdb2.txt](https://github.com/ArmaLife/Framework/files/401594/extdb2.txt)

**Comment by NiiRoZz** [comment]
Test with last commit

**Comment by coresync2k** [comment]
no save license/gear/stats
[extdb2.txt](https://github.com/ArmaLife/Framework/files/401626/extdb2.txt)

**Comment by BoGuu** [comment]
@coresync2k 

Test with: http://hastebin.com/wafeqoxize.lua

**Comment by coresync2k** [comment]
@BoGuu it works.
Here the debug.dll for any reasons ^^
[extdb2.txt](https://github.com/ArmaLife/Framework/files/401677/extdb2.txt)

**Comment by coresync2k** [comment]
thx for fixing this :)

**Comment by BoGuu** [comment]
Welcome, glad it's fixed
