### ISSUE TITLE
SQL unaccesible

### ISSUE THREAD

**Issue by FlashModz** [ArmaLife/Framework#919]
### Expected behaviour

Server OK
### Actual behaviour

18:14:41 Bob Jacky uses modified data file
18:14:41 Player Bob Jacky connecting.
18:14:43 Player Bob Jacky connected (id=76561198264021855).
Unaccessible
18:29:23 Unknown attribute shadown
18:38:32 Client: Remote object 3:0 not found

Players are connected, just information not saved into db and error to shop

### Steps to reproduce the behaviour 
1. place the mission.pbo and connect

### RPT and/or extDB2 logs (if applicable)
extdb2 : 
http://pastebin.com/J985ic65

RPT : 

http://pastebin.com/wpQEftCN

----

*Arma 3* version: 1.62
*Arma 3* branch: Main Branch

**Comment by FlashModz** [comment]
Tested on mariaDBserver 10 and Msql Server 5.7.11.
error persist

**Comment by BoGuu** [comment]
You're not using vanilla files, evident from both your RPT and extDB log. I mean for heavens sake it even says starting Tanoa Life Client. Perhaps you should seek help from the person that made this instead.

**Comment by tkcjesse** [comment]
You also have a shitload of errors.

**Comment by Jawshy** [comment]
Contributing to ArmaLife → [Issues](https://github.com/ArmaLife/Framework/blob/master/.github/CONTRIBUTING.md#issues): 

> #### Before creating a new issue make sure to... 
> [...] 
> * **...check that you are using the latest files from the master branch.** 
>   * If your files are behind then it is possible that the issue you are reporting has already been fixed in a recent commit. 
> * **...check that you have not modified the files from what is on the repository.** 
>   * If your files are different from what is on the repository then it is possible that a change that you made is what is causing the issue. 

Reading as gone out-of-fashion, ladies and gentlemen.

**Comment by FlashModz** [comment]
This error comes from mission.sqm your github and tanoa file your github, that's why I ask you for help

**Comment by FlashModz** [comment]
Mission.sql : https://github.com/ArmaLife/Framework/tree/master/Altis_Life.Altis
Files : 

https://github.com/ArmaLife/Framework/tree/master/Tanoa_Life.Tanoa
https://github.com/ArmaLife/Framework/tree/master/life_server
https://github.com/ArmaLife/Framework/tree/master/BEFilters
https://github.com/ArmaLife/extDB2

**Comment by Jawshy** [comment]
@FlashModz: 

#### From the [linked RPT file](http://pastebin.com/wpQEftCN): 

> 18:14:49  Mission file: RM1_Life (__CUR_MP)
> 18:14:49  Mission world: Tanoa
> [...]
> 18:14:57 "--------------------------------- Starting Tanoa Life Client Init ----------------------------------"

#### Repository files: 

[Framework/**Altis_Life.Altis**/mission.sqm](https://github.com/ArmaLife/Framework/blob/3cf593f70b37d6c68655c05f6b8a8d08e5602f0d/Altis_Life.Altis/mission.sqm)

[Framework/life_client/core/init.sqf](https://github.com/ArmaLife/Framework/blob/109df16fd14f5191b3e4caf3eaad087870c274c8/life_client/core/init.sqf#L17): 

```sqf
diag_log "--------------------------------- Starting Altis Life Client Init ----------------------------------";
```

**Comment by FlashModz** [comment]
Wtf, i'm sûre, 
I will start and if the error is really from me I will make you my apologies, but you show me is for me very clear indeed

**Comment by FlashModz** [comment]
just by chance, would you have the option of adding a mission.sqm tanoa?

**Comment by Jawshy** [comment]
> just by chance, would you have the option of adding a mission.sqm tanoa?

@FlashModz, this repository will not have full support for Tanoa anytime in the foreseeable future. [AsYetUntitled/Framework](https://github.com/AsYetUntitled/Framework) has ongoing support for Tanoa.

**Comment by FlashModz** [comment]
Thanks a lot bro, your work and your respons has just perfect for me, Big Thanks

**Comment by FlashModz** [comment]
All test have been not resolve problems https://github.com/AsYetUntitled/Framework/issues/74
