### ISSUE TITLE
Gang Armament

### ISSUE THREAD

**Issue by numpty9989** [ArmaLife/Framework#921]
### Expected behaviour
access to gang armament

### Actual behaviour
Nothing

### Steps to reproduce the behaviour 
1. Make gang
2. capture hideout
3 go to armament
4. No option???

No Errors In RPT or EXTDB

### RPT and/or extDB2 logs (if applicable)
<If there are error messages in your RPT and/or extDB2 logs then you can either paste the error message(s) here or you can upload your RPT or extDB2 log file(s) to GitHub.>
<See https://community.bistudio.com/wiki/Crash_Files for where to find your Arma 3 RPT logs.>
<If your error messages are long, or you are posting a full RPT, please use paste/haste-bin!!>

----

Launcher version:  <In the Arma 3 launcher go to OPTIONS and click the version info below to copy it to your clipboard>

Game version: 

Branch:

**Comment by fresqo** [comment]
2 hideout addaction conditions are using _b = nearestBuilding (getPosATL player);
1 hideout addaction condition is using  _b = (nearestObjects[getPosATL player,[""Land_u_Barracks_V2_F"",""Land_i_Barracks_V2_F""],25]) select 0;

Whoever is sorting map can please adjust?

**Comment by numpty9989** [comment]
ok  thanks

**Comment by Jawshy** [comment]
@fresqo, do you even [markdown](https://guides.github.com/features/mastering-markdown/)?

**Comment by numpty9989** [comment]
lol was bugging me so quickly wrote it soz xD

**Comment by Jawshy** [comment]
You think you're fresqo?

**Comment by numpty9989** [comment]
Lol misread the @fresco lol

**Comment by tkcjesse** [comment]
Now we're randomly tagging people that aren't even part of this? Fresco != Fresqo

**Comment by numpty9989** [comment]
this is the top of mt code it looks ok whats wrong ???
```
private["_group","_hideout","_action","_cpRate","_cP","_progressBar","_title","_titleText","_ui","_flagTexture"];
_hideout = (nearestObjects[getPosATL player,["Land_u_Barracks_V2_F","Land_i_Barracks_V2_F"],25]) select 0;
_group = _hideout getVariable ["gangOwner",grpNull];
```

**Comment by fresqo** [comment]
### MY REPLY TO @numpty9989 <h3>
I haven't seen the map, but the flagpole should be within **25 metres** of the building or this code
> **(nearestObjects[getPosATL player,["Land_u_Barracks_V2_F","Land_i_Barracks_V2_F"],25]) select 0;**
 
won't work (plus the building needs to be a **(typeOf "Land_u_Barracks_V2_F" or "Land_i_Barracks_V2_F")**. Unless you change it to the same as 
> **nearestBuilding (getPosATL player);**

In other news...
> if (fresqo isEqualTo fresqo) then {fresqo = fresqo} else {fresqo = fresqo};

**Comment by numpty9989** [comment]
> I haven't seen the map, but the flagpole should be within 25 metres of the building or this code

(nearestObjects[getPosATL player,["Land_u_Barracks_V2_F","Land_i_Barracks_V2_F"],25]) select 0;


it is as its stock that section of code i sent is stock 4.4 R3 from fn_capturehideout

**Comment by fresqo** [comment]
@numpty9989 yeah but on the Map (in editor) how far is the flagpole from the hideout building? and what typeOf building is it?

**Comment by numpty9989** [comment]
sorry for long code `dataType="Object";
			class PositionInfo
			{
				position[]={11682.772,41.965408,15912.511};
				angles[]={0,0.00046888617,0};
			};
			side="Empty";
			class Attributes
			{
				skill=0.60000002;
				init="this allowDamage false; this enableSimulation false; this addAction[localize""STR_MAR_Armament"",life_fnc_weaponShopMenu,""gang"",0,false,false,"""",' _b = nearestBuilding (getPosATL player); !isNil {_b getVariable ""gangOwner""} && {(_b getVariable ""gangOwner"") == (group player)} && playerSide isEqualTo civilian ']; this addAction[localize""STR_Shops_C_Gang"",life_fnc_clothingMenu,""gang_clothing"",0,false,false,"""",' _b = nearestBuilding (getPosATL player); !isNil {_b getVariable ""gangOwner""} && {(_b getVariable ""gangOwner"") == (group player)} && playerSide isEqualTo civilian ']; this setVariable [""realname"",""Gang Armament""];";
			};
			id=637;
			type="Land_Pallet_MilBoxes_F";
			atlOffset=3.2467079;
			class CustomAttributes
			{
				class Attribute0
				{
					property="allowDamage";
					expression="_this allowdamage _value;";
					class Value
					{
						class data
						{
							class type
							{
								type[]=
								{
									"BOOL"
								};
							};
							value=0;
						};
					};
				};
				nAttributes=1;
			};
		};`

**Comment by numpty9989** [comment]
thats from mission.sqm

**Comment by fresqo** [comment]
@numpty9989 please check in editor. 
**Please check** 
- distance between flagpole to building.
- distance from armament crate to building.
- what is the nearest typeOf building to flagpole.
- what is the nearest typeOf building to armament crate

**Comment by numpty9989** [comment]
ill check in morning goin bed and post my finding

**Comment by tkcjesse** [comment]
So.......

**Comment by numpty9989** [comment]
Flagpole isnt too far probs 10 m armament crate is in building as gan hideout hasnt been moved soz been really busy

**Comment by tkcjesse** [comment]
Ah so this is not on the default repo? You've moved things and such? If someone can recreate on default repo it'll get reopened. Or if you provide more info on an UNMODIFIED repo.

**Comment by numpty9989** [comment]
I have not moved anything in the gang hideout its still in original position doesnt anyone here understand english. Its been tested on a stock mission of 4.4r3

**Comment by implusehunter** [comment]
ive had this issue too i tryed it on a misson that i added stuff to then re downloaded a FULLY STOCK MISSON still same issue fix it

**Comment by implusehunter** [comment]
ive also been on multiple servers with this version and its broken on all of then after talking to staff on some of the servers they said its been like that since they downloaded the stock misson
