### ISSUE TITLE
SQM for Tanoa Life?

### ISSUE THREAD

**Issue by MJRamon** [ArmaLife/Framework#923]
SQM for Tanoa Life is missing. If we need to generate it, how do we do it?

**Comment by BoGuu** [comment]
See https://github.com/AsYetUntitled/Framework

Arma Life do not have a Tanoa build, or SQM currently, and foreseeably

**Comment by Jawshy** [comment]
This was already asked in https://github.com/ArmaLife/Framework/issues/891. 

Contributing to ArmaLife → [Issues](https://github.com/ArmaLife/Framework/blob/master/.github/CONTRIBUTING.md#before-creating-a-new-issue-make-sure-to): 

> * **...check that the issue you are reporting does not already exist.** 
>   * If it does exist and it is still open then you may wish to add more information to that issue in a comment. 
>   * If it does exist but it has been closed then comment on **that** issue instead of creating a new one. An [organisation member](https://github.com/orgs/ArmaLife/people) will then decide if the issue needs to be reopened. 

[Search results for SQM](https://github.com/ArmaLife/Framework/issues?utf8=%E2%9C%93&q=SQM%20).
